SV Publisher - Native C++ Module: SvController Class Reference
SvController Class Reference
#include <sv_controller.h>
Public Member Functions
uint32_t addPublisher ()
int removePublisher (uint32_t id)
int removeAllPublishers ()
SvPublisherInstance * getPublisher (uint32_t id)
uint32_t getPublisherCount () const
int configurePublisher (uint32_t id, const PublisherConfig &config)
int setPublisherEquations (uint32_t id, const char *equations)
int startAll ()
int stopAll ()
int resetAll ()
bool isRunning () const
int setSendMode (int mode)
int getSendMode () const
int setDuration (uint32_t seconds, bool repeat, bool infinite, uint32_t count)
uint32_t getRemainingSeconds () const
uint32_t getCurrentRepeatCycle () const
bool isDurationComplete () const
void setUsbPadSize (int bytes)
int getUsbPadSize () const
void setUsbMinGapUs (int us)
int getUsbMinGapUs () const
const char * getLastError () const
Static Public Member Functions
static SvController & instance ()
Private Member Functions
SvController ()
~SvController ()
SvController (const SvController &)=delete
SvController & operator= (const SvController &)=delete
SvPublisherInstance * findPublisher (uint32_t id)
bool checkDurationElapsed () const
void writerLoop ()
void writerLoopBatch ()
void writerLoopImmediate ()
void elevateThreadPriority ()
void restoreThreadPriority ()
Static Private Member Functions
static void spinPause ()
Private Attributes
std::vector< std::unique_ptr< SvPublisherInstance > > m_publishers
uint32_t m_nextId = 1
std::mutex m_mutex
SharedBuffer m_sharedBuffer
std::thread m_writerThread
std::atomic< bool > m_running {false}
int m_sendMode = 0
uint32_t m_durationSeconds = 0
bool m_repeatEnabled = false
bool m_repeatInfinite = false
uint32_t m_repeatCount = 0
std::atomic< uint32_t > m_repeatCycle {0}
std::atomic< bool > m_durationComplete {false}
std::atomic< uint64_t > m_startTimeMs {0}
int m_usbPadSize = 0
int m_usbMinGapUs = 0
char m_errorBuf [512]
Detailed Description
Definition at line 123 of file sv_controller.h.
Constructor & Destructor Documentation
SvController() [1/2]
SvController::SvController () private
Definition at line 146 of file sv_controller.cc.
{
    m_errorBuf[0] = '\0';
}
References m_errorBuf.
Referenced by instance(), operator=(), and SvController().
~SvController()
SvController::~SvController () private
Definition at line 151 of file sv_controller.cc.
{
    stopAll();
}
References stopAll().
SvController() [2/2]
SvController::SvController (const SvController &) private delete
References SvController().
Member Function Documentation
addPublisher()
uint32_t SvController::addPublisher ()
Definition at line 160 of file sv_controller.cc.
{
    std::lock_guard<std::mutex> lock(m_mutex);
    uint32_t id = m_nextId++;
    auto pub = std::make_unique<SvPublisherInstance>(id);
    m_publishers.push_back(std::move(pub));
    printf("[controller] Added publisher %u (total: %zu)\n",
           id, m_publishers.size());
    return id;
}
References m_mutex, m_nextId, and m_publishers.
Referenced by sv_mp_add_publisher().
checkDurationElapsed()
bool SvController::checkDurationElapsed () const private
Definition at line 304 of file sv_controller.cc.
{
    if (m_durationSeconds == 0) return false;
    uint64_t elapsed = npcap_stats_get_time_ms() - m_startTimeMs.load();
    return elapsed >= (uint64_t)m_durationSeconds * 1000ULL;
}
References m_durationSeconds, m_startTimeMs, and npcap_stats_get_time_ms().
Referenced by writerLoopBatch(), and writerLoopImmediate().
configurePublisher()
int SvController::configurePublisher (uint32_t id, const PublisherConfig & config)
Definition at line 240 of file sv_controller.cc.
{
    std::lock_guard<std::mutex> lock(m_mutex);
    auto* pub = findPublisher(id);
    if (!pub) {
        snprintf(m_errorBuf, sizeof(m_errorBuf), "Publisher %u not found", id);
        return -1;
    }
    return pub->configure(config);
}
References findPublisher(), m_errorBuf, and m_mutex.
Referenced by sv_mp_configure_publisher().
elevateThreadPriority()
void SvController::elevateThreadPriority () private
Definition at line 315 of file sv_controller.cc.
{
#ifdef _WIN32
    timeBeginPeriod(1);
    SetThreadPriority(GetCurrentThread(), THREAD_PRIORITY_TIME_CRITICAL);
    SetThreadAffinityMask(GetCurrentThread(), 1ULL << 0);
    printf("[controller] Writer thread: TIME_CRITICAL, core 0\n");
#endif
}
Referenced by writerLoopBatch(), and writerLoopImmediate().
findPublisher()
SvPublisherInstance * SvController::findPublisher (uint32_t id) private
Definition at line 222 of file sv_controller.cc.
{
    for (auto& pub : m_publishers) {
        if (pub->getId() == id) return pub.get();
    }
    return nullptr;
}
References m_publishers.
Referenced by configurePublisher(), getPublisher(), and setPublisherEquations().
getCurrentRepeatCycle()
uint32_t SvController::getCurrentRepeatCycle () const inline
Definition at line 151 of file sv_controller.h.
{ return m_repeatCycle.load(); }
References m_repeatCycle.
Referenced by sv_mp_get_current_repeat_cycle().
getLastError()
const char * SvController::getLastError () const inline
Definition at line 160 of file sv_controller.h.
{ return m_errorBuf; }
References m_errorBuf.
Referenced by sv_mp_get_last_error().
getPublisher()
SvPublisherInstance * SvController::getPublisher (uint32_t id)
Definition at line 216 of file sv_controller.cc.
{
    std::lock_guard<std::mutex> lock(m_mutex);
    return findPublisher(id);
}
References findPublisher(), and m_mutex.
getPublisherCount()
uint32_t SvController::getPublisherCount () const
Definition at line 230 of file sv_controller.cc.
{
    std::lock_guard<std::mutex> lock(m_mutex);
    return (uint32_t)m_publishers.size();
}
References m_mutex, and m_publishers.
Referenced by sv_mp_get_publisher_count().
getRemainingSeconds()
uint32_t SvController::getRemainingSeconds () const
Definition at line 295 of file sv_controller.cc.
{
    if (m_durationSeconds == 0 || !m_running.load()) return m_durationSeconds;
    uint64_t elapsed = npcap_stats_get_time_ms() - m_startTimeMs.load();
    uint64_t total   = (uint64_t)m_durationSeconds * 1000ULL;
    return (elapsed >= total) ? 0 : (uint32_t)((total - elapsed) / 1000);
}
References m_durationSeconds, m_running, m_startTimeMs, and npcap_stats_get_time_ms().
Referenced by sv_mp_get_remaining_seconds().
getSendMode()
int SvController::getSendMode () const inline
Definition at line 146 of file sv_controller.h.
{ return m_sendMode; }
References m_sendMode.
Referenced by sv_mp_get_send_mode().
getUsbMinGapUs()
int SvController::getUsbMinGapUs () const inline
Definition at line 158 of file sv_controller.h.
{ return m_usbMinGapUs; }
References m_usbMinGapUs.
Referenced by sv_mp_get_usb_min_gap_us().
getUsbPadSize()
int SvController::getUsbPadSize () const inline
Definition at line 156 of file sv_controller.h.
{ return m_usbPadSize; }
References m_usbPadSize.
Referenced by sv_mp_get_usb_pad_size().
instance()
SvController & SvController::instance () static
Definition at line 140 of file sv_controller.cc.
{
    static SvController s_instance;
    return s_instance;
}
References SvController().
Referenced by sv_mp_add_publisher(), sv_mp_configure_publisher(), sv_mp_get_current_repeat_cycle(), sv_mp_get_last_error(), sv_mp_get_publisher_count(), sv_mp_get_remaining_seconds(), sv_mp_get_send_mode(), sv_mp_get_usb_min_gap_us(), sv_mp_get_usb_pad_size(), sv_mp_is_duration_complete(), sv_mp_is_running(), sv_mp_remove_all_publishers(), sv_mp_remove_publisher(), sv_mp_reset_all(), sv_mp_set_duration(), sv_mp_set_publisher_equations(), sv_mp_set_send_mode(), sv_mp_set_usb_min_gap_us(), sv_mp_set_usb_pad_size(), sv_mp_start_all(), and sv_mp_stop_all().
isDurationComplete()
bool SvController::isDurationComplete () const inline
Definition at line 152 of file sv_controller.h.
{ return m_durationComplete.load(); }
References m_durationComplete.
Referenced by sv_mp_is_duration_complete().
isRunning()
bool SvController::isRunning () const inline
Definition at line 142 of file sv_controller.h.
{ return m_running.load(); }
References m_running.
Referenced by sv_mp_is_running().
operator=()
SvController & SvController::operator= (const SvController &) private delete
References SvController().
removeAllPublishers()
int SvController::removeAllPublishers ()
Definition at line 196 of file sv_controller.cc.
{
    std::lock_guard<std::mutex> lock(m_mutex);
    if (m_running.load()) {
        snprintf(m_errorBuf, sizeof(m_errorBuf),
                 "Cannot remove publishers while running");
        return -1;
    }
    size_t count = m_publishers.size();
    m_publishers.clear();
    m_nextId = 1;  /* Reset ID counter for clean session */
    m_sharedBuffer.clear();
    printf("[controller] Removed all %zu publisher(s), ID counter reset\n",
           count);
    return 0;
}
References m_errorBuf, m_mutex, m_nextId, m_publishers, m_running, and m_sharedBuffer.
Referenced by sv_mp_remove_all_publishers().
removePublisher()
int SvController::removePublisher (uint32_t id)
Definition at line 173 of file sv_controller.cc.
{
    std::lock_guard<std::mutex> lock(m_mutex);
    if (m_running.load()) {
        snprintf(m_errorBuf, sizeof(m_errorBuf),
                 "Cannot remove publisher while running");
        return -1;
    }
    for (auto it = m_publishers.begin(); it != m_publishers.end(); ++it) {
        if ((*it)->getId() == id) {
            printf("[controller] Removed publisher %u\n", id);
            m_publishers.erase(it);
            return 0;
        }
    }
    snprintf(m_errorBuf, sizeof(m_errorBuf),
             "Publisher %u not found", id);
    return -1;
}
References m_errorBuf, m_mutex, m_publishers, and m_running.
Referenced by sv_mp_remove_publisher().
resetAll()
int SvController::resetAll ()
Definition at line 439 of file sv_controller.cc.
{
    printf("[controller] ═══════════════════════════════════════════\n");
    printf("[controller] FULL RESET — clearing all state\n");
    /* 1. Stop transmission if running */
    if (m_running.load()) {
        m_running.store(false);
        if (m_writerThread.joinable())
            m_writerThread.join();
    }
    /* 2. Clear shared buffer */
    m_sharedBuffer.clear();
    /* 3. Clear all publishers (frees frame caches) */
    {
        std::lock_guard<std::mutex> lock(m_mutex);
        m_publishers.clear();
        m_nextId = 1;
    }
    /* 4. Reset global settings to defaults */
    m_sendMode         = 0;
    m_durationSeconds  = 0;
    m_repeatEnabled    = false;
    m_repeatInfinite   = false;
    m_repeatCount      = 0;
    m_repeatCycle.store(0);
    m_durationComplete.store(false);
    m_startTimeMs.store(0);
    m_usbPadSize       = 0;
    m_usbMinGapUs      = 0;
    m_errorBuf[0] = '\0';
    /* 5. Reset stats */
    npcap_stats_reset();
    /* 6. Stop single-publisher if it was running */
    extern int npcap_publisher_stop(void);
    npcap_publisher_stop();
    printf("[controller] Reset complete — all memory freed, all state cleared\n");
    printf("[controller] ═══════════════════════════════════════════\n");
    return 0;
}
References m_durationComplete, m_durationSeconds, m_errorBuf, m_mutex, m_nextId, m_publishers, m_repeatCount, m_repeatCycle, m_repeatEnabled, m_repeatInfinite, m_running, m_sendMode, m_sharedBuffer, m_startTimeMs, m_usbMinGapUs, m_usbPadSize, m_writerThread, npcap_publisher_stop(), and npcap_stats_reset().
Referenced by sv_mp_reset_all().
restoreThreadPriority()
void SvController::restoreThreadPriority () private
Definition at line 325 of file sv_controller.cc.
{
#ifdef _WIN32
    timeEndPeriod(1);
    SetThreadPriority(GetCurrentThread(), THREAD_PRIORITY_NORMAL);
    SYSTEM_INFO si;
    GetSystemInfo(&si);
    SetThreadAffinityMask(GetCurrentThread(),
                          (1ULL << si.dwNumberOfProcessors) - 1);
#endif
}
Referenced by writerLoopBatch(), and writerLoopImmediate().
setDuration()
int SvController::setDuration (uint32_t seconds, bool repeat, bool infinite, uint32_t count)
Definition at line 284 of file sv_controller.cc.
{
    m_durationSeconds = seconds;
    m_repeatEnabled   = repeat;
    m_repeatInfinite  = infinite;
    m_repeatCount     = count;
    m_repeatCycle.store(0);
    return 0;
}
References m_durationSeconds, m_repeatCount, m_repeatCycle, m_repeatEnabled, and m_repeatInfinite.
Referenced by sv_mp_set_duration().
setPublisherEquations()
int SvController::setPublisherEquations (uint32_t id, const char * equations)
Definition at line 251 of file sv_controller.cc.
{
    std::lock_guard<std::mutex> lock(m_mutex);
    auto* pub = findPublisher(id);
    if (!pub) {
        snprintf(m_errorBuf, sizeof(m_errorBuf), "Publisher %u not found", id);
        return -1;
    }
    return pub->setEquations(equations);
}
References findPublisher(), m_errorBuf, and m_mutex.
Referenced by sv_mp_set_publisher_equations().
setSendMode()
int SvController::setSendMode (int mode)
Definition at line 266 of file sv_controller.cc.
{
    if (mode < 0 || mode > 3) {
        snprintf(m_errorBuf, sizeof(m_errorBuf),
                 "Invalid send mode: %d (0=auto, 1=batch, 2=immediate, 3=usb)", mode);
        return -1;
    }
    if (m_running.load()) {
        snprintf(m_errorBuf, sizeof(m_errorBuf),
                 "Cannot change send mode while running");
        return -1;
    }
    m_sendMode = mode;
    const char* names[] = {"AUTO", "SendQueue (batch)", "SendPacket (immediate)", "USB-Optimized (spin+gap)"};
    printf("[controller] Send mode: %s\n", names[mode]);
    return 0;
}
References m_errorBuf, m_running, and m_sendMode.
Referenced by sv_mp_set_send_mode().
setUsbMinGapUs()
void SvController::setUsbMinGapUs (int us) inline
Definition at line 157 of file sv_controller.h.
{ m_usbMinGapUs = (us >= 0 && us <= 5000) ? us : 0; }
References m_usbMinGapUs.
Referenced by sv_mp_set_usb_min_gap_us().
setUsbPadSize()
void SvController::setUsbPadSize (int bytes) inline
Definition at line 155 of file sv_controller.h.
{ m_usbPadSize = (bytes >= 0 && bytes <= 1522) ? bytes : 0; }
References m_usbPadSize.
Referenced by sv_mp_set_usb_pad_size().
spinPause()
void SvController::spinPause () inline static private
Definition at line 202 of file sv_controller.h.
{
#if defined(_MSC_VER)
        _mm_pause();
#elif defined(__GNUC__) || defined(__clang__)
        __builtin_ia32_pause();
#endif
    }
Referenced by writerLoopBatch(), and writerLoopImmediate().
startAll()
int SvController::startAll ()
Definition at line 341 of file sv_controller.cc.
{
    if (m_running.load()) {
        snprintf(m_errorBuf, sizeof(m_errorBuf), "Already running");
        return -1;
    }
    if (npcap_publisher_is_running()) {
        snprintf(m_errorBuf, sizeof(m_errorBuf),
                 "Single-publisher is already running. Stop it before using multi-publisher.");
        return -1;
    }
    if (!npcap_is_open()) {
        snprintf(m_errorBuf, sizeof(m_errorBuf), "No network interface open");
        return -1;
    }
    std::lock_guard<std::mutex> lock(m_mutex);
    if (m_publishers.empty()) {
        snprintf(m_errorBuf, sizeof(m_errorBuf), "No publishers added");
        return -1;
    }
    printf("[controller] ═══════════════════════════════════════════\n");
    printf("[controller] Starting %zu publisher(s)...\n", m_publishers.size());
    /*
     * STEP 1: Pre-build frames for each publisher (SEQUENTIAL)
     * Each publisher sets the global encoder config and builds its frames.
     * Sequential execution avoids encoder state conflicts.
     */
    for (auto& pub : m_publishers) {
        if (pub->getState() < SvPublisherInstance::CONFIGURED) {
            printf("[controller] WARNING: publisher %u not configured, skipping\n",
                   pub->getId());
            continue;
        }
        int ret = pub->prebuildFrames();
        if (ret != 0) {
            snprintf(m_errorBuf, sizeof(m_errorBuf),
                     "Publisher %u: prebuild failed: %s",
                     pub->getId(), pub->getLastError());
            return -1;
        }
    }
    /*
     * STEP 2: Build SharedBuffer (merged interleaved schedule)
     * Merges all publishers' internal buffers into one sorted timeline.
     */
    m_sharedBuffer.buildFromPublishers(m_publishers);
    if (m_sharedBuffer.empty()) {
        snprintf(m_errorBuf, sizeof(m_errorBuf),
                 "Shared buffer is empty — no frames built");
        return -1;
    }
    /*
     * STEP 3: Start writer thread
     */
    m_startTimeMs.store(npcap_stats_get_time_ms());
    m_durationComplete.store(false);
    m_repeatCycle.store(0);
    m_running.store(true);
    m_writerThread = std::thread(&SvController::writerLoop, this);
    printf("[controller] Writer thread started\n");
    printf("[controller] ═══════════════════════════════════════════\n");
    return 0;
}
References SvPublisherInstance::CONFIGURED, m_durationComplete, m_errorBuf, m_mutex, m_publishers, m_repeatCycle, m_running, m_sharedBuffer, m_startTimeMs, m_writerThread, npcap_is_open(), npcap_publisher_is_running(), npcap_stats_get_time_ms(), and writerLoop().
Referenced by sv_mp_start_all().
stopAll()
int SvController::stopAll ()
Definition at line 414 of file sv_controller.cc.
{
    if (!m_running.load()) return 0;
    printf("[controller] Stopping...\n");
    m_running.store(false);
    if (m_writerThread.joinable())
        m_writerThread.join();
    m_sharedBuffer.clear();
    /* Defense-in-depth: clear all publishers so stale state never persists.
     * The frontend always does removeAll + add + configure before each start,
     * so keeping old publishers serves no purpose and risks accumulation bugs. */
    {
        std::lock_guard<std::mutex> lock(m_mutex);
        m_publishers.clear();
        m_nextId = 1;
    }
    printf("[controller] Stopped (publishers cleared)\n");
    return 0;
}
References m_mutex, m_nextId, m_publishers, m_running, m_sharedBuffer, and m_writerThread.
Referenced by sv_mp_stop_all(), and ~SvController().
writerLoop()
void SvController::writerLoop () private
Definition at line 491 of file sv_controller.cc.
{
    bool useBatch = false;
    switch (m_sendMode) {
    case 1: /* Force batch */
        useBatch = npcap_sendqueue_available();
        if (!useBatch)
            printf("[controller] WARNING: batch mode requested but sendqueue "
                   "not available, falling back to immediate\n");
        break;
    case 2: /* Force immediate */
        useBatch = false;
        break;
    case 3: /* USB-Optimized: force immediate + spin pacing */
        useBatch = false;
        break;
    case 0: /* Auto */
    default:
        useBatch = npcap_sendqueue_available();
        break;
    }
    if (useBatch)
        writerLoopBatch();
    else
        writerLoopImmediate();
}
References m_sendMode, npcap_sendqueue_available(), writerLoopBatch(), and writerLoopImmediate().
Referenced by startAll().
writerLoopBatch()
void SvController::writerLoopBatch () private
Definition at line 532 of file sv_controller.cc.
{
    printf("[controller] Writer: BATCH mode (sendqueue)\n");
    elevateThreadPriority();
    npcap_stats_reset();
    npcap_stats_session_start();
    const size_t schedSize    = m_sharedBuffer.size();
    const uint64_t cycle_us   = m_sharedBuffer.getCycleDuration();
    const size_t frameLen     = m_sharedBuffer[0].frameLen; /* approx, for sizing */
    /* Aggregate rate across all publishers */
    uint64_t aggregate_pps = (cycle_us > 0)
        ? (schedSize * 1000000ULL / cycle_us) : schedSize;
    /* Wire time per frame at 1 Gbps */
    double wire_time_us = (double)(frameLen + 20) * 8.0 / 1000.0;
    printf("[controller] Schedule: %zu entries, cycle: %llu us, "
           "aggregate: %llu pps\n",
           schedSize, (unsigned long long)cycle_us,
           (unsigned long long)aggregate_pps);
    uint64_t totalPackets = 0;
    /*--------------------------------------------------------------
     * TIER 1 — PRECISE (≤4800 pps aggregate)
     *--------------------------------------------------------------*/
    if (aggregate_pps <= 4800) {
        printf("[controller] Tier: PRECISE (1 pkt/queue, sync=1)\n");
        while (m_running.load() && !checkDurationElapsed()) {
            uint64_t ts_accum = 0;
            for (size_t i = 0; i < schedSize; i++) {
                if (!m_running.load() || checkDurationElapsed()) break;
                const ScheduleEntry& e = m_sharedBuffer[i];
                unsigned int qsize = (unsigned int)(e.frameLen + 24 + 4096);
                void* q = npcap_queue_create(qsize);
                if (!q) continue;
                npcap_queue_add(q, e.framePtr, e.frameLen, ts_accum);
                /* Interval to NEXT entry */
                if (i + 1 < schedSize) {
                    ts_accum += m_sharedBuffer[i + 1].timestamp_us
                              - e.timestamp_us;
                } else {
                    /* Wrap: end of cycle → start of next cycle */
                    ts_accum += cycle_us - e.timestamp_us;
                }
                unsigned int sent = npcap_queue_transmit(q, 1);
                if (sent > 0) {
                    totalPackets++;
                    npcap_stats_record_packet(e.frameLen);
                }
                npcap_queue_destroy(q);
            }
        }
    }
    /*--------------------------------------------------------------
     * TIER 2 — HIGH-SPEED (>4800 pps aggregate)
     *--------------------------------------------------------------*/
    else {
        /* Adaptive batch: target ~500µs of wire time per burst */
        uint64_t batchSize = (uint64_t)(500.0 / wire_time_us);
        if (batchSize < 50)   batchSize = 50;
        if (batchSize > 5000) batchSize = 5000;
        if (batchSize > schedSize) batchSize = schedSize;
        double batchInterval_us = (double)batchSize * 1000000.0
                                  / (double)aggregate_pps;
        auto batchDuration = std::chrono::nanoseconds(
            (int64_t)(batchInterval_us * 1000.0));
        printf("[controller] Tier: HIGH-SPEED (batch=%llu, sync=0, "
               "QPC pacing)\n", (unsigned long long)batchSize);
        unsigned int qmemsize =
            (unsigned int)(batchSize * (frameLen + 24) + 4096);
        auto nextBatch = std::chrono::high_resolution_clock::now();
        uint64_t batchCount = 0;
        uint64_t schedIdx = 0;
        while (m_running.load() && !checkDurationElapsed()) {
            void* q = npcap_queue_create(qmemsize);
            if (!q) {
                std::this_thread::sleep_for(std::chrono::milliseconds(1));
                continue;
            }
            for (uint64_t b = 0; b < batchSize; b++) {
                const ScheduleEntry& e =
                    m_sharedBuffer[schedIdx % schedSize];
                npcap_queue_add(q, e.framePtr, e.frameLen, 0);
                schedIdx++;
            }
            unsigned int sent = npcap_queue_transmit(q, 0);
            if (sent > 0) {
                uint32_t pkts = sent / (uint32_t)frameLen;
                totalPackets += pkts;
                for (uint32_t p = 0; p < pkts; p++)
                    npcap_stats_record_packet(frameLen);
            }
            npcap_queue_destroy(q);
            /* QPC spin-wait for pacing */
            nextBatch += batchDuration;
            while (std::chrono::high_resolution_clock::now() < nextBatch)
                spinPause();
            /* Re-anchor every 200 batches to prevent drift */
            batchCount++;
            if ((batchCount % 200) == 0)
                nextBatch = std::chrono::high_resolution_clock::now();
        }
    }
    restoreThreadPriority();
    /* Handle repeat */
    if (checkDurationElapsed() && m_repeatEnabled) {
        m_repeatCycle.fetch_add(1);
        uint32_t cycle = m_repeatCycle.load();
        if (m_repeatInfinite || cycle < m_repeatCount) {
            printf("[controller] Repeat cycle %u\n", cycle + 1);
            m_startTimeMs.store(npcap_stats_get_time_ms());
            m_durationComplete.store(false);
            writerLoopBatch();
            return;
        }
    }
    npcap_stats_session_end();
    if (checkDurationElapsed()) {
        m_durationComplete.store(true);
        m_running.store(false);
    }
    printf("[controller] Batch writer complete: %llu packets\n",
           (unsigned long long)totalPackets);
}
References checkDurationElapsed(), elevateThreadPriority(), ScheduleEntry::frameLen, ScheduleEntry::framePtr, m_durationComplete, m_repeatCount, m_repeatCycle, m_repeatEnabled, m_repeatInfinite, m_running, m_sharedBuffer, m_startTimeMs, npcap_queue_add(), npcap_queue_create(), npcap_queue_destroy(), npcap_queue_transmit(), npcap_stats_get_time_ms(), npcap_stats_record_packet(), npcap_stats_reset(), npcap_stats_session_end(), npcap_stats_session_start(), restoreThreadPriority(), spinPause(), ScheduleEntry::timestamp_us, and writerLoopBatch().
Referenced by writerLoop(), and writerLoopBatch().
writerLoopImmediate()
void SvController::writerLoopImmediate () private
Definition at line 689 of file sv_controller.cc.
{
    printf("[controller] Writer: IMMEDIATE mode (pcap_sendpacket)\n");
    elevateThreadPriority();
    npcap_stats_reset();
    npcap_stats_session_start();
    const size_t schedSize  = m_sharedBuffer.size();
    const uint64_t cycle_us = m_sharedBuffer.getCycleDuration();
    uint64_t aggregate_pps = (cycle_us > 0)
        ? (schedSize * 1000000ULL / cycle_us) : schedSize;
    /* Choose pacing */
    enum Pacing { SLEEP, SPIN, NONE };
    Pacing pacing;
    bool usbMode = (m_sendMode == 3);
    if (usbMode)                     pacing = SPIN;  /* USB: always spin */
    else if (aggregate_pps <= 4800)  pacing = SLEEP;
    else if (aggregate_pps <= 50000) pacing = SPIN;
    else                             pacing = NONE;
    const char* pacingNames[] = {"SLEEP+SPIN", "SPIN", "NONE"};
    printf("[controller] Pacing: %s, aggregate: %llu pps%s\n",
           pacingNames[pacing], (unsigned long long)aggregate_pps,
           usbMode ? " [USB-OPTIMIZED]" : "");
    int usbPadSize = m_usbPadSize;
    int usbGapUs = (m_usbMinGapUs > 0) ? m_usbMinGapUs : 130;
    if (usbMode) {
        printf("[controller] USB-OPTIMIZED: gap=%d us", usbGapUs);
        if (usbPadSize > 0)
            printf(", padding=%d bytes", usbPadSize);
        printf("\n");
    }
    uint64_t totalPackets  = 0;
    uint64_t totalFailures = 0;
    uint64_t schedIdx      = 0;
    /* Calculate average interval between consecutive schedule entries */
    double avg_interval_us = (aggregate_pps > 0)
        ? (1000000.0 / (double)aggregate_pps) : 250.0;
    auto intervalDur = std::chrono::nanoseconds(
        (int64_t)(avg_interval_us * 1000.0));
    /* Epoch-based absolute scheduling (industry standard).
     *
     * target[N] = epoch + N * interval
     *
     * This ensures the average packet rate is EXACTLY correct regardless
     * of how long each pcap_sendpacket() call takes.
     *
     * If pcap_sendpacket takes longer than the interval, we fall behind
     * schedule. To handle this:
     *   - Small lag: send next packet immediately (natural catch-up)
     *   - Large lag (>3 intervals behind): re-anchor epoch to prevent
     *     unbounded bursts of back-to-back packets
     *
     * This is the same approach used by tcpreplay, Linux pktgen, and
     * professional traffic generators (DPDK TRex, MoonGen, etc.).
     */
    auto epoch = std::chrono::high_resolution_clock::now();
    uint64_t pktNum = 0;
    while (m_running.load() && !checkDurationElapsed()) {
        const ScheduleEntry& e = m_sharedBuffer[schedIdx % schedSize];
        int result;
        if (usbMode && usbPadSize > 0 && usbPadSize > (int)e.frameLen) {
            result = npcap_send_packet_padded(e.framePtr, e.frameLen, (size_t)usbPadSize);
        } else {
            result = npcap_send_packet(e.framePtr, e.frameLen);
        }
        if (result == 0) {
            totalPackets++;
            npcap_stats_record_packet(e.frameLen);
        } else {
            totalFailures++;
            npcap_stats_record_failure();
        }
        schedIdx++;
        pktNum++;
        if (pacing == NONE)
            continue;
        /* Absolute target for the NEXT packet */
        auto target = epoch + pktNum * intervalDur;
        auto now    = std::chrono::high_resolution_clock::now();
        if (target <= now) {
            /* Behind schedule — check how far */
            auto behind = std::chrono::duration_cast<
                std::chrono::nanoseconds>(now - target);
            if (behind > intervalDur) {
                /* Behind by >1 interval — re-anchor to prevent burst.
                 * Allows at most 1 catch-up packet (small lag < 1 interval)
                 * but prevents back-to-back bursts of 3-4 packets that
                 * appear as 0.000000 deltas in Wireshark. */
                epoch  = now;
                pktNum = 0;
            }
            /* USB mode: even when behind, enforce minimum gap between
             * sends so the USB host controller doesn't batch packets
             * into the same microframe (125µs). Configurable gap. */
            if (usbMode) {
                auto minTarget = now + std::chrono::microseconds(usbGapUs);
                while (std::chrono::high_resolution_clock::now() < minTarget)
                    spinPause();
            }
            continue;
        }
        /* Ahead of schedule — pace to exact target */
        switch (pacing) {
        case SLEEP: {
            auto remaining = std::chrono::duration_cast<
                std::chrono::microseconds>(target - now);
            if (remaining.count() > 80)
                std::this_thread::sleep_for(
                    remaining - std::chrono::microseconds(80));
            while (std::chrono::high_resolution_clock::now() < target)
                spinPause();
            break;
        }
        case SPIN:
            while (std::chrono::high_resolution_clock::now() < target)
                spinPause();
            break;
        default:
            break;
        }
    }
    restoreThreadPriority();
    /* Handle repeat */
    if (checkDurationElapsed() && m_repeatEnabled) {
        m_repeatCycle.fetch_add(1);
        uint32_t cycle = m_repeatCycle.load();
        if (m_repeatInfinite || cycle < m_repeatCount) {
            printf("[controller] Repeat cycle %u\n", cycle + 1);
            m_startTimeMs.store(npcap_stats_get_time_ms());
            m_durationComplete.store(false);
            writerLoopImmediate();
            return;
        }
    }
    npcap_stats_session_end();
    if (checkDurationElapsed()) {
        m_durationComplete.store(true);
        m_running.store(false);
    }
    printf("[controller] Immediate writer complete: %llu sent, %llu failed\n",
           (unsigned long long)totalPackets,
           (unsigned long long)totalFailures);
}
References checkDurationElapsed(), elevateThreadPriority(), ScheduleEntry::frameLen, ScheduleEntry::framePtr, m_durationComplete, m_repeatCount, m_repeatCycle, m_repeatEnabled, m_repeatInfinite, m_running, m_sendMode, m_sharedBuffer, m_startTimeMs, m_usbMinGapUs, m_usbPadSize, npcap_send_packet(), npcap_send_packet_padded(), npcap_stats_get_time_ms(), npcap_stats_record_failure(), npcap_stats_record_packet(), npcap_stats_reset(), npcap_stats_session_end(), npcap_stats_session_start(), restoreThreadPriority(), spinPause(), and writerLoopImmediate().
Referenced by writerLoop(), and writerLoopImmediate().
Field Documentation
m_durationComplete
std::atomic<bool> SvController::m_durationComplete {false} private
Definition at line 187 of file sv_controller.h.
{false};
Referenced by isDurationComplete(), resetAll(), startAll(), writerLoopBatch(), and writerLoopImmediate().
m_durationSeconds
uint32_t SvController::m_durationSeconds = 0 private
Definition at line 182 of file sv_controller.h.
Referenced by checkDurationElapsed(), getRemainingSeconds(), resetAll(), and setDuration().
m_errorBuf
char SvController::m_errorBuf[512] private
Definition at line 193 of file sv_controller.h.
Referenced by configurePublisher(), getLastError(), removeAllPublishers(), removePublisher(), resetAll(), setPublisherEquations(), setSendMode(), startAll(), and SvController().
m_mutex
std::mutex SvController::m_mutex mutable private
Definition at line 171 of file sv_controller.h.
Referenced by addPublisher(), configurePublisher(), getPublisher(), getPublisherCount(), removeAllPublishers(), removePublisher(), resetAll(), setPublisherEquations(), startAll(), and stopAll().
m_nextId
uint32_t SvController::m_nextId = 1 private
Definition at line 170 of file sv_controller.h.
Referenced by addPublisher(), removeAllPublishers(), resetAll(), and stopAll().
m_publishers
std::vector<std::unique_ptr<SvPublisherInstance> > SvController::m_publishers private
Definition at line 169 of file sv_controller.h.
Referenced by addPublisher(), findPublisher(), getPublisherCount(), removeAllPublishers(), removePublisher(), resetAll(), startAll(), and stopAll().
m_repeatCount
uint32_t SvController::m_repeatCount = 0 private
Definition at line 185 of file sv_controller.h.
Referenced by resetAll(), setDuration(), writerLoopBatch(), and writerLoopImmediate().
m_repeatCycle
std::atomic<uint32_t> SvController::m_repeatCycle {0} private
Definition at line 186 of file sv_controller.h.
{0};
Referenced by getCurrentRepeatCycle(), resetAll(), setDuration(), startAll(), writerLoopBatch(), and writerLoopImmediate().
m_repeatEnabled
bool SvController::m_repeatEnabled = false private
Definition at line 183 of file sv_controller.h.
Referenced by resetAll(), setDuration(), writerLoopBatch(), and writerLoopImmediate().
m_repeatInfinite
bool SvController::m_repeatInfinite = false private
Definition at line 184 of file sv_controller.h.
Referenced by resetAll(), setDuration(), writerLoopBatch(), and writerLoopImmediate().
m_running
std::atomic<bool> SvController::m_running {false} private
Definition at line 178 of file sv_controller.h.
{false};
Referenced by getRemainingSeconds(), isRunning(), removeAllPublishers(), removePublisher(), resetAll(), setSendMode(), startAll(), stopAll(), writerLoopBatch(), and writerLoopImmediate().
m_sendMode
int SvController::m_sendMode = 0 private
Definition at line 181 of file sv_controller.h.
Referenced by getSendMode(), resetAll(), setSendMode(), writerLoop(), and writerLoopImmediate().
m_sharedBuffer
SharedBuffer SvController::m_sharedBuffer private
Definition at line 174 of file sv_controller.h.
Referenced by removeAllPublishers(), resetAll(), startAll(), stopAll(), writerLoopBatch(), and writerLoopImmediate().
m_startTimeMs
std::atomic<uint64_t> SvController::m_startTimeMs {0} private
Definition at line 188 of file sv_controller.h.
{0};
Referenced by checkDurationElapsed(), getRemainingSeconds(), resetAll(), startAll(), writerLoopBatch(), and writerLoopImmediate().
m_usbMinGapUs
int SvController::m_usbMinGapUs = 0 private
Definition at line 191 of file sv_controller.h.
Referenced by getUsbMinGapUs(), resetAll(), setUsbMinGapUs(), and writerLoopImmediate().
m_usbPadSize
int SvController::m_usbPadSize = 0 private
Definition at line 190 of file sv_controller.h.
Referenced by getUsbPadSize(), resetAll(), setUsbPadSize(), and writerLoopImmediate().
m_writerThread
std::thread SvController::m_writerThread private
Definition at line 177 of file sv_controller.h.
Referenced by resetAll(), startAll(), and stopAll().
The documentation for this class was generated from the following files:
sv_controller.h
sv_controller.cc