SV Publisher - Native C++ Module: equation_processor.cc File Reference
equation_processor.cc File Reference
Equation Processing Implementation.
#include "equation_processor.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>
#include <ctype.h>
Macros
#define strtok_r strtok_s
#define strdup _strdup
Functions
static void trim (char *str)
static const char * find_ci (const char *str, const char *pattern)
static double parse_amplitude (const char *eq)
static double parse_frequency (const char *eq, double defaultFreq)
static double parse_phase (const char *eq)
static EqWaveformType parse_wavetype (const char *eq)
int eq_processor_init (EqProcessor *proc, double defaultFreq, uint32_t sampleRate)
void eq_processor_reset (EqProcessor *proc)
int eq_parse_equation (const char *equation, EqChannelData *ch, double defaultFreq)
int eq_load_equations (EqProcessor *proc, const char *equations)
int eq_set_channel_equation (EqProcessor *proc, const char *channelId, const char *equation)
int32_t eq_generate_sample (const EqChannelData *ch, double t)
int32_t eq_generate_sample_indexed (const EqChannelData *ch, uint64_t idx, uint32_t rate)
int eq_generate_all_samples (const EqProcessor *proc, double t, int32_t *samples, int max)
void eq_generate_9_2le_samples (const EqProcessor *proc, double t, int32_t curr[4], int32_t volt[4])
const EqChannelData * eq_get_channel (const EqProcessor *proc, const char *id)
const EqChannelData * eq_get_channel_by_index (const EqProcessor *proc, int idx)
int eq_get_channel_count (const EqProcessor *proc)
void eq_print_all (const EqProcessor *proc)
void eq_get_stats (const EqProcessor *proc, int *parsed, int *errors)
int eq_validate_equation (const char *eq)
Detailed Description
Equation Processing Implementation.
Parses waveform equations and generates samples for IEC 61850-9-2LE.
Definition in file equation_processor.cc.
Macro Definition Documentation
strdup
#define strdup _strdup
Definition at line 17 of file equation_processor.cc.
Referenced by eq_load_equations().
strtok_r
#define strtok_r strtok_s
Definition at line 16 of file equation_processor.cc.
Referenced by eq_load_equations().
Function Documentation
eq_generate_9_2le_samples()
void eq_generate_9_2le_samples (const EqProcessor * proc, double t, int32_t curr[4], int32_t volt[4])
Definition at line 308 of file equation_processor.cc.
{
    if (!proc || !curr || !volt) return;
    static const char* curr_ids[] = {"Ia", "Ib", "Ic", "In"};
    static const char* volt_ids[] = {"Va", "Vb", "Vc", "Vn"};
    for (int i = 0; i < 4; i++) {
        const EqChannelData* ch = eq_get_channel(proc, curr_ids[i]);
        curr[i] = ch ? eq_generate_sample(ch, t) : 0;
    }
    for (int i = 0; i < 4; i++) {
        const EqChannelData* ch = eq_get_channel(proc, volt_ids[i]);
        volt[i] = ch ? eq_generate_sample(ch, t) : 0;
    }
}
References eq_generate_sample(), and eq_get_channel().
eq_generate_all_samples()
int eq_generate_all_samples (const EqProcessor * proc, double t, int32_t * samples, int max)
Definition at line 298 of file equation_processor.cc.
{
    if (!proc || !samples) return 0;
    int count = (proc->channelCount < max) ? proc->channelCount : max;
    for (int i = 0; i < count; i++) {
        samples[i] = eq_generate_sample(&proc->channels[i], t);
    }
    return count;
}
References EqProcessor::channelCount, EqProcessor::channels, and eq_generate_sample().
eq_generate_sample()
int32_t eq_generate_sample (const EqChannelData * ch, double t)
Definition at line 272 of file equation_processor.cc.
{
    if (!ch || ch->isZero || !ch->isValid) return 0;
    double omega = EQ_TWO_PI * ch->frequency;
    double angle = omega * t + ch->phaseOffset;
    double value = 0.0;
    switch (ch->waveType) {
        case EQ_WAVE_SINE:   value = ch->amplitude * sin(angle); break;
        case EQ_WAVE_COSINE: value = ch->amplitude * cos(angle); break;
        case EQ_WAVE_SQUARE: value = ch->amplitude * (sin(angle) >= 0 ? 1.0 : -1.0); break;
        case EQ_WAVE_TRIANGLE: {
            double phase = fmod(angle, EQ_TWO_PI);
            if (phase < 0) phase += EQ_TWO_PI;
            value = ch->amplitude * (phase < EQ_PI ? (2.0 * phase / EQ_PI - 1.0) : (3.0 - 2.0 * phase / EQ_PI));
            break;
        }
    }
    return (int32_t)(value * ch->scaleFactor);
}
References EqChannelData::amplitude, EQ_PI, EQ_TWO_PI, EQ_WAVE_COSINE, EQ_WAVE_SINE, EQ_WAVE_SQUARE, EQ_WAVE_TRIANGLE, EqChannelData::frequency, EqChannelData::isValid, EqChannelData::isZero, EqChannelData::phaseOffset, EqChannelData::scaleFactor, and EqChannelData::waveType.
Referenced by eq_generate_9_2le_samples(), eq_generate_all_samples(), and eq_generate_sample_indexed().
eq_generate_sample_indexed()
int32_t eq_generate_sample_indexed (const EqChannelData * ch, uint64_t idx, uint32_t rate)
Definition at line 294 of file equation_processor.cc.
{
    return (rate == 0) ? 0 : eq_generate_sample(ch, (double)idx / (double)rate);
}
References eq_generate_sample().
eq_get_channel()
const EqChannelData * eq_get_channel (const EqProcessor * proc, const char * id)
Definition at line 328 of file equation_processor.cc.
{
    if (!proc || !id) return NULL;
    for (int i = 0; i < proc->channelCount; i++) {
        if (strcmp(proc->channels[i].id, id) == 0) return &proc->channels[i];
    }
    return NULL;
}
References EqProcessor::channelCount, EqProcessor::channels, and EqChannelData::id.
Referenced by eq_generate_9_2le_samples().
eq_get_channel_by_index()
const EqChannelData * eq_get_channel_by_index (const EqProcessor * proc, int idx)
Definition at line 337 of file equation_processor.cc.
{
    if (!proc || idx < 0 || idx >= proc->channelCount) return NULL;
    return &proc->channels[idx];
}
References EqProcessor::channelCount, and EqProcessor::channels.
eq_get_channel_count()
int eq_get_channel_count (const EqProcessor * proc)
Definition at line 342 of file equation_processor.cc.
{
    return proc ? proc->channelCount : 0;
}
References EqProcessor::channelCount.
eq_get_stats()
void eq_get_stats (const EqProcessor * proc, int * parsed, int * errors)
Definition at line 365 of file equation_processor.cc.
{
    if (!proc) return;
    if (parsed) *parsed = proc->channelCount;
    if (errors) *errors = proc->parseErrors;
}
References EqProcessor::channelCount, and EqProcessor::parseErrors.
eq_load_equations()
int eq_load_equations (EqProcessor * proc, const char * equations)
Definition at line 206 of file equation_processor.cc.
{
    if (!proc || !equations) return -1;
    eq_processor_reset(proc);
    printf("[eq] Loading equations (freq=%.0f Hz, rate=%u)\n",
           proc->defaultFrequency, proc->sampleRate);
    char* str = strdup(equations);
    if (!str) return -1;
    char* saveptr;
    char* token = strtok_r(str, "|", &saveptr);
    int count = 0;
    while (token && proc->channelCount < EQ_MAX_CHANNELS) {
        char* colon = strchr(token, ':');
        if (!colon) { token = strtok_r(NULL, "|", &saveptr); continue; }
        *colon = '\0';
        char* id = token;
        char* eq = colon + 1;
        trim(id);
        trim(eq);
        EqChannelData* ch = &proc->channels[proc->channelCount];
        strncpy(ch->id, id, EQ_MAX_ID_LEN - 1);
        if (eq_parse_equation(eq, ch, proc->defaultFrequency) == 0) {
            printf("[eq] %s: amp=%.1f, freq=%.0f Hz, phase=%.1f°\n",
                   ch->id, ch->amplitude, ch->frequency, ch->phaseOffset * 180.0 / EQ_PI);
            proc->channelCount++;
            count++;
        } else {
            proc->parseErrors++;
        }
        token = strtok_r(NULL, "|", &saveptr);
    }
    free(str);
    printf("[eq] Loaded %d channels\n", count);
    return count;
}
References EqChannelData::amplitude, EqProcessor::channelCount, EqProcessor::channels, EqProcessor::defaultFrequency, EQ_MAX_CHANNELS, EQ_MAX_ID_LEN, eq_parse_equation(), EQ_PI, eq_processor_reset(), EqChannelData::frequency, EqChannelData::id, EqProcessor::parseErrors, EqChannelData::phaseOffset, EqProcessor::sampleRate, strdup, strtok_r, and trim().
eq_parse_equation()
int eq_parse_equation (const char * equation, EqChannelData * ch, double defaultFreq)
Definition at line 176 of file equation_processor.cc.
{
    if (!ch) return -1;
    ch->amplitude = 0;
    ch->frequency = defaultFreq;
    ch->phaseOffset = 0;
    ch->scaleFactor = 1000.0;
    ch->isZero = 0;
    ch->isValid = 0;
    ch->waveType = EQ_WAVE_SINE;
    if (!equation || !equation[0] || strcmp(equation, "0") == 0 || strcmp(equation, "0.0") == 0) {
        ch->isZero = 1;
        ch->isValid = 1;
        return 0;
    }
    strncpy(ch->equation, equation, EQ_MAX_EQUATION_LEN - 1);
    ch->equation[EQ_MAX_EQUATION_LEN - 1] = '\0';
    trim(ch->equation);
    ch->amplitude = parse_amplitude(ch->equation);
    ch->frequency = parse_frequency(ch->equation, defaultFreq);
    ch->phaseOffset = parse_phase(ch->equation);
    ch->waveType = parse_wavetype(ch->equation);
    ch->isValid = 1;
    return 0;
}
References EqChannelData::amplitude, EQ_MAX_EQUATION_LEN, EQ_WAVE_SINE, EqChannelData::equation, EqChannelData::frequency, EqChannelData::isValid, EqChannelData::isZero, parse_amplitude(), parse_frequency(), parse_phase(), parse_wavetype(), EqChannelData::phaseOffset, EqChannelData::scaleFactor, trim(), and EqChannelData::waveType.
Referenced by eq_load_equations(), and eq_set_channel_equation().
eq_print_all()
void eq_print_all (const EqProcessor * proc)
Definition at line 350 of file equation_processor.cc.
{
    if (!proc) return;
    printf("\n=== Equation Processor ===\n");
    printf("Frequency: %.0f Hz, Rate: %u\n", proc->defaultFrequency, proc->sampleRate);
    printf("Channels: %d, Errors: %d\n\n", proc->channelCount, proc->parseErrors);
    for (int i = 0; i < proc->channelCount; i++) {
        const EqChannelData* ch = &proc->channels[i];
        printf("[%d] %s: amp=%.1f, freq=%.0f, phase=%.1f°\n",
               i, ch->id, ch->amplitude, ch->frequency, ch->phaseOffset * 180.0 / EQ_PI);
    }
    printf("==========================\n\n");
}
References EqChannelData::amplitude, EqProcessor::channelCount, EqProcessor::channels, EqProcessor::defaultFrequency, EQ_PI, EqChannelData::frequency, EqChannelData::id, EqProcessor::parseErrors, EqChannelData::phaseOffset, and EqProcessor::sampleRate.
eq_processor_init()
int eq_processor_init (EqProcessor * proc, double defaultFreq, uint32_t sampleRate)
Definition at line 153 of file equation_processor.cc.
{
    if (!proc) return -1;
    memset(proc, 0, sizeof(EqProcessor));
    proc->defaultFrequency = defaultFreq;
    proc->sampleRate = sampleRate;
    for (int i = 0; i < EQ_MAX_CHANNELS; i++) {
        proc->channels[i].frequency = defaultFreq;
        proc->channels[i].scaleFactor = 1000.0;
        proc->channels[i].isZero = 1;
    }
    return 0;
}
References EqProcessor::channels, EqProcessor::defaultFrequency, EQ_MAX_CHANNELS, EqChannelData::frequency, EqChannelData::isZero, EqProcessor::sampleRate, and EqChannelData::scaleFactor.
Referenced by eq_processor_reset().
eq_processor_reset()
void eq_processor_reset (EqProcessor * proc)
Definition at line 169 of file equation_processor.cc.
{
    if (!proc) return;
    double freq = proc->defaultFrequency;
    uint32_t rate = proc->sampleRate;
    eq_processor_init(proc, freq, rate);
}
References EqProcessor::defaultFrequency, eq_processor_init(), and EqProcessor::sampleRate.
Referenced by eq_load_equations().
eq_set_channel_equation()
int eq_set_channel_equation (EqProcessor * proc, const char * channelId, const char * equation)
Definition at line 251 of file equation_processor.cc.
{
    if (!proc || !channelId) return -1;
    int idx = -1;
    for (int i = 0; i < proc->channelCount; i++) {
        if (strcmp(proc->channels[i].id, channelId) == 0) { idx = i; break; }
    }
    if (idx < 0) {
        if (proc->channelCount >= EQ_MAX_CHANNELS) return -1;
        idx = proc->channelCount++;
        strncpy(proc->channels[idx].id, channelId, EQ_MAX_ID_LEN - 1);
    }
    return eq_parse_equation(equation, &proc->channels[idx], proc->defaultFrequency);
}
References EqProcessor::channelCount, EqProcessor::channels, EqProcessor::defaultFrequency, EQ_MAX_CHANNELS, EQ_MAX_ID_LEN, eq_parse_equation(), and EqChannelData::id.
eq_validate_equation()
int eq_validate_equation (const char * eq)
Definition at line 371 of file equation_processor.cc.
{
    if (!eq || !eq[0] || strcmp(eq, "0") == 0) return 1;
    if (find_ci(eq, "sin") || find_ci(eq, "cos") || find_ci(eq, "square") || find_ci(eq, "triangle")) return 1;
    char* endptr;
    strtod(eq, &endptr);
    return (*endptr == '\0' || isspace((unsigned char)*endptr));
}
References find_ci().
find_ci()
const char * find_ci (const char * str, const char * pattern) static
Definition at line 36 of file equation_processor.cc.
{
    if (!str || !pattern) return NULL;
    size_t slen = strlen(str), plen = strlen(pattern);
    if (plen > slen) return NULL;
    for (size_t i = 0; i <= slen - plen; i++) {
        int match = 1;
        for (size_t j = 0; j < plen && match; j++) {
            if (tolower((unsigned char)str[i+j]) != tolower((unsigned char)pattern[j]))
                match = 0;
        }
        if (match) return str + i;
    }
    return NULL;
}
Referenced by eq_validate_equation(), and parse_wavetype().
parse_amplitude()
double parse_amplitude (const char * eq) static
Definition at line 57 of file equation_processor.cc.
{
    if (!eq) return 0.0;
    const char* star = strchr(eq, '*');
    if (!star) return atof(eq);
    char buf[64];
    size_t len = star - eq;
    if (len >= sizeof(buf)) len = sizeof(buf) - 1;
    strncpy(buf, eq, len);
    buf[len] = '\0';
    trim(buf);
    return atof(buf);
}
References trim().
Referenced by eq_parse_equation().
parse_frequency()
double parse_frequency (const char * eq, double defaultFreq) static
Definition at line 73 of file equation_processor.cc.
{
    if (!eq) return defaultFreq;
    /* Normalize string */
    char norm[EQ_MAX_EQUATION_LEN];
    size_t j = 0;
    for (size_t i = 0; eq[i] && j < sizeof(norm) - 1; i++) {
        if (!isspace((unsigned char)eq[i])) {
            norm[j++] = tolower((unsigned char)eq[i]);
        }
    }
    norm[j] = '\0';
    /* Find "pi*" pattern */
    const char* pi = strstr(norm, "pi*");
    if (!pi) pi = strstr(norm, "pi ");
    if (!pi) return defaultFreq;
    const char* start = pi + 3;
    while (*start == '*' || *start == ' ') start++;
    const char* end = strstr(start, "*t");
    if (!end) end = strchr(start, 't');
    if (!end) end = strchr(start, ')');
    if (!end) return defaultFreq;
    char buf[32];
    size_t len = end - start;
    while (len > 0 && (start[len-1] == '*' || start[len-1] == ' ')) len--;
    if (len >= sizeof(buf)) len = sizeof(buf) - 1;
    strncpy(buf, start, len);
    buf[len] = '\0';
    double freq = atof(buf);
    return (freq > 0 && freq < 1e9) ? freq : defaultFreq;
}
References EQ_MAX_EQUATION_LEN.
Referenced by eq_parse_equation().
parse_phase()
double parse_phase (const char * eq) static
Definition at line 111 of file equation_processor.cc.
{
    if (!eq) return 0.0;
    char norm[EQ_MAX_EQUATION_LEN];
    size_t j = 0;
    for (size_t i = 0; eq[i] && j < sizeof(norm) - 1; i++) {
        if (!isspace((unsigned char)eq[i])) {
            norm[j++] = tolower((unsigned char)eq[i]);
        }
    }
    norm[j] = '\0';
    const char* t = strstr(norm, "*t");
    if (!t) t = strchr(norm, 't');
    if (!t) return 0.0;
    const char* after = t + 1;
    if (*after == '*') after++;
    /* Common phase patterns */
    if (strstr(after, "-2*pi/3") || strstr(after, "-2pi/3")) return -EQ_TWO_PI / 3.0;
    if (strstr(after, "+2*pi/3") || strstr(after, "+2pi/3") || strstr(after, "2*pi/3")) return EQ_TWO_PI / 3.0;
    if (strstr(after, "-4*pi/3") || strstr(after, "-4pi/3")) return -4.0 * EQ_PI / 3.0;
    if (strstr(after, "+4*pi/3") || strstr(after, "+4pi/3")) return 4.0 * EQ_PI / 3.0;
    if (strstr(after, "-pi/2")) return -EQ_PI / 2.0;
    if (strstr(after, "+pi/2")) return EQ_PI / 2.0;
    return 0.0;
}
References EQ_MAX_EQUATION_LEN, EQ_PI, and EQ_TWO_PI.
Referenced by eq_parse_equation().
parse_wavetype()
EqWaveformType parse_wavetype (const char * eq) static
Definition at line 141 of file equation_processor.cc.
{
    if (!eq) return EQ_WAVE_SINE;
    if (find_ci(eq, "cos(")) return EQ_WAVE_COSINE;
    if (find_ci(eq, "square") || find_ci(eq, "sqr(")) return EQ_WAVE_SQUARE;
    if (find_ci(eq, "triangle") || find_ci(eq, "tri(")) return EQ_WAVE_TRIANGLE;
    return EQ_WAVE_SINE;
}
References EQ_WAVE_COSINE, EQ_WAVE_SINE, EQ_WAVE_SQUARE, EQ_WAVE_TRIANGLE, and find_ci().
Referenced by eq_parse_equation().
trim()
void trim (char * str) static
Definition at line 24 of file equation_processor.cc.
{
    if (!str || !*str) return;
    char* start = str;
    while (*start && isspace((unsigned char)*start)) start++;
    char* end = start + strlen(start) - 1;
    while (end > start && isspace((unsigned char)*end)) *end-- = '\0';
    if (start != str) memmove(str, start, strlen(start) + 1);
}
Referenced by eq_load_equations(), eq_parse_equation(), and parse_amplitude().