SV Publisher - Native C++ Module: equation_processor.h File Reference
equation_processor.h File Reference
Equation Processing for SV Publisher.
#include <stdint.h>
#include <stddef.h>
Data Structures
struct EqChannelData
struct EqProcessor
Macros
#define EQ_MAX_CHANNELS 20
#define EQ_MAX_EQUATION_LEN 256
#define EQ_MAX_ID_LEN 32
#define EQ_PI 3.14159265358979323846
#define EQ_TWO_PI (2.0 * EQ_PI)
Enumerations
enum EqWaveformType { EQ_WAVE_SINE = 0 , EQ_WAVE_COSINE = 1 , EQ_WAVE_SQUARE = 2 , EQ_WAVE_TRIANGLE = 3 }
Functions
int eq_processor_init (EqProcessor *proc, double defaultFreq, uint32_t sampleRate)
void eq_processor_reset (EqProcessor *proc)
int eq_load_equations (EqProcessor *proc, const char *equations)
int eq_parse_equation (const char *equation, EqChannelData *channel, double defaultFreq)
int eq_set_channel_equation (EqProcessor *proc, const char *channelId, const char *equation)
int32_t eq_generate_sample (const EqChannelData *channel, double t)
int32_t eq_generate_sample_indexed (const EqChannelData *channel, uint64_t sampleIndex, uint32_t sampleRate)
int eq_generate_all_samples (const EqProcessor *proc, double t, int32_t *samples, int maxSamples)
void eq_generate_9_2le_samples (const EqProcessor *proc, double t, int32_t currents[4], int32_t voltages[4])
const EqChannelData * eq_get_channel (const EqProcessor *proc, const char *channelId)
const EqChannelData * eq_get_channel_by_index (const EqProcessor *proc, int index)
int eq_get_channel_count (const EqProcessor *proc)
void eq_print_all (const EqProcessor *proc)
void eq_get_stats (const EqProcessor *proc, int *totalParsed, int *parseErrors)
int eq_validate_equation (const char *equation)
Detailed Description
Equation Processing for SV Publisher.
Parses waveform equations and generates samples for IEC 61850-9-2LE.
Supported equation format: "100 * sin(2 * PI * 50 * t)" -> amp=100, freq=50 Hz "325 * sin(2 * PI * 50 * t - 2*PI/3)" -> amp=325, freq=50 Hz, phase=-120° "0" -> zero signal
Definition in file equation_processor.h.
Macro Definition Documentation
EQ_MAX_CHANNELS
#define EQ_MAX_CHANNELS 20
Definition at line 27 of file equation_processor.h.
Referenced by eq_load_equations(), eq_processor_init(), and eq_set_channel_equation().
EQ_MAX_EQUATION_LEN
#define EQ_MAX_EQUATION_LEN 256
Definition at line 28 of file equation_processor.h.
Referenced by eq_parse_equation(), parse_frequency(), and parse_phase().
EQ_MAX_ID_LEN
#define EQ_MAX_ID_LEN 32
Definition at line 29 of file equation_processor.h.
Referenced by eq_load_equations(), and eq_set_channel_equation().
EQ_PI
#define EQ_PI 3.14159265358979323846
Definition at line 30 of file equation_processor.h.
Referenced by eq_generate_sample(), eq_load_equations(), eq_print_all(), and parse_phase().
EQ_TWO_PI
#define EQ_TWO_PI (2.0 * EQ_PI)
Definition at line 31 of file equation_processor.h.
Referenced by eq_generate_sample(), and parse_phase().
Enumeration Type Documentation
EqWaveformType
enum EqWaveformType
Enumerator
EQ_WAVE_SINE
EQ_WAVE_COSINE
EQ_WAVE_SQUARE
EQ_WAVE_TRIANGLE
Definition at line 37 of file equation_processor.h.
             {
    EQ_WAVE_SINE = 0,
    EQ_WAVE_COSINE = 1,
    EQ_WAVE_SQUARE = 2,
    EQ_WAVE_TRIANGLE = 3
} EqWaveformType;
Function Documentation
eq_generate_9_2le_samples()
void eq_generate_9_2le_samples (const EqProcessor * proc, double t, int32_t currents[4], int32_t voltages[4])
Definition at line 308 of file equation_processor.cc.
{
    if (!proc || !curr || !volt) return;
    static const char* curr_ids[] = {"Ia", "Ib", "Ic", "In"};
    static const char* volt_ids[] = {"Va", "Vb", "Vc", "Vn"};
    for (int i = 0; i < 4; i++) {
        const EqChannelData* ch = eq_get_channel(proc, curr_ids[i]);
        curr[i] = ch ? eq_generate_sample(ch, t) : 0;
    }
    for (int i = 0; i < 4; i++) {
        const EqChannelData* ch = eq_get_channel(proc, volt_ids[i]);
        volt[i] = ch ? eq_generate_sample(ch, t) : 0;
    }
}
References eq_generate_sample(), and eq_get_channel().
eq_generate_all_samples()
int eq_generate_all_samples (const EqProcessor * proc, double t, int32_t * samples, int maxSamples)
Definition at line 298 of file equation_processor.cc.
{
    if (!proc || !samples) return 0;
    int count = (proc->channelCount < max) ? proc->channelCount : max;
    for (int i = 0; i < count; i++) {
        samples[i] = eq_generate_sample(&proc->channels[i], t);
    }
    return count;
}
References EqProcessor::channelCount, EqProcessor::channels, and eq_generate_sample().
eq_generate_sample()
int32_t eq_generate_sample (const EqChannelData * channel, double t)
Definition at line 272 of file equation_processor.cc.
{
    if (!ch || ch->isZero || !ch->isValid) return 0;
    double omega = EQ_TWO_PI * ch->frequency;
    double angle = omega * t + ch->phaseOffset;
    double value = 0.0;
    switch (ch->waveType) {
        case EQ_WAVE_SINE:   value = ch->amplitude * sin(angle); break;
        case EQ_WAVE_COSINE: value = ch->amplitude * cos(angle); break;
        case EQ_WAVE_SQUARE: value = ch->amplitude * (sin(angle) >= 0 ? 1.0 : -1.0); break;
        case EQ_WAVE_TRIANGLE: {
            double phase = fmod(angle, EQ_TWO_PI);
            if (phase < 0) phase += EQ_TWO_PI;
            value = ch->amplitude * (phase < EQ_PI ? (2.0 * phase / EQ_PI - 1.0) : (3.0 - 2.0 * phase / EQ_PI));
            break;
        }
    }
    return (int32_t)(value * ch->scaleFactor);
}
References EqChannelData::amplitude, EQ_PI, EQ_TWO_PI, EQ_WAVE_COSINE, EQ_WAVE_SINE, EQ_WAVE_SQUARE, EQ_WAVE_TRIANGLE, EqChannelData::frequency, EqChannelData::isValid, EqChannelData::isZero, EqChannelData::phaseOffset, EqChannelData::scaleFactor, and EqChannelData::waveType.
Referenced by eq_generate_9_2le_samples(), eq_generate_all_samples(), and eq_generate_sample_indexed().
eq_generate_sample_indexed()
int32_t eq_generate_sample_indexed (const EqChannelData * channel, uint64_t sampleIndex, uint32_t sampleRate)
Definition at line 294 of file equation_processor.cc.
{
    return (rate == 0) ? 0 : eq_generate_sample(ch, (double)idx / (double)rate);
}
References eq_generate_sample().
eq_get_channel()
const EqChannelData * eq_get_channel (const EqProcessor * proc, const char * channelId)
Definition at line 328 of file equation_processor.cc.
{
    if (!proc || !id) return NULL;
    for (int i = 0; i < proc->channelCount; i++) {
        if (strcmp(proc->channels[i].id, id) == 0) return &proc->channels[i];
    }
    return NULL;
}
References EqProcessor::channelCount, EqProcessor::channels, and EqChannelData::id.
Referenced by eq_generate_9_2le_samples().
eq_get_channel_by_index()
const EqChannelData * eq_get_channel_by_index (const EqProcessor * proc, int index)
Definition at line 337 of file equation_processor.cc.
{
    if (!proc || idx < 0 || idx >= proc->channelCount) return NULL;
    return &proc->channels[idx];
}
References EqProcessor::channelCount, and EqProcessor::channels.
eq_get_channel_count()
int eq_get_channel_count (const EqProcessor * proc)
Definition at line 342 of file equation_processor.cc.
{
    return proc ? proc->channelCount : 0;
}
References EqProcessor::channelCount.
eq_get_stats()
void eq_get_stats (const EqProcessor * proc, int * totalParsed, int * parseErrors)
Definition at line 365 of file equation_processor.cc.
{
    if (!proc) return;
    if (parsed) *parsed = proc->channelCount;
    if (errors) *errors = proc->parseErrors;
}
References EqProcessor::channelCount, and EqProcessor::parseErrors.
eq_load_equations()
int eq_load_equations (EqProcessor * proc, const char * equations)
Definition at line 206 of file equation_processor.cc.
{
    if (!proc || !equations) return -1;
    eq_processor_reset(proc);
    printf("[eq] Loading equations (freq=%.0f Hz, rate=%u)\n",
           proc->defaultFrequency, proc->sampleRate);
    char* str = strdup(equations);
    if (!str) return -1;
    char* saveptr;
    char* token = strtok_r(str, "|", &saveptr);
    int count = 0;
    while (token && proc->channelCount < EQ_MAX_CHANNELS) {
        char* colon = strchr(token, ':');
        if (!colon) { token = strtok_r(NULL, "|", &saveptr); continue; }
        *colon = '\0';
        char* id = token;
        char* eq = colon + 1;
        trim(id);
        trim(eq);
        EqChannelData* ch = &proc->channels[proc->channelCount];
        strncpy(ch->id, id, EQ_MAX_ID_LEN - 1);
        if (eq_parse_equation(eq, ch, proc->defaultFrequency) == 0) {
            printf("[eq] %s: amp=%.1f, freq=%.0f Hz, phase=%.1f°\n",
                   ch->id, ch->amplitude, ch->frequency, ch->phaseOffset * 180.0 / EQ_PI);
            proc->channelCount++;
            count++;
        } else {
            proc->parseErrors++;
        }
        token = strtok_r(NULL, "|", &saveptr);
    }
    free(str);
    printf("[eq] Loaded %d channels\n", count);
    return count;
}
References EqChannelData::amplitude, EqProcessor::channelCount, EqProcessor::channels, EqProcessor::defaultFrequency, EQ_MAX_CHANNELS, EQ_MAX_ID_LEN, eq_parse_equation(), EQ_PI, eq_processor_reset(), EqChannelData::frequency, EqChannelData::id, EqProcessor::parseErrors, EqChannelData::phaseOffset, EqProcessor::sampleRate, strdup, strtok_r, and trim().
eq_parse_equation()
int eq_parse_equation (const char * equation, EqChannelData * channel, double defaultFreq)
Definition at line 176 of file equation_processor.cc.
{
    if (!ch) return -1;
    ch->amplitude = 0;
    ch->frequency = defaultFreq;
    ch->phaseOffset = 0;
    ch->scaleFactor = 1000.0;
    ch->isZero = 0;
    ch->isValid = 0;
    ch->waveType = EQ_WAVE_SINE;
    if (!equation || !equation[0] || strcmp(equation, "0") == 0 || strcmp(equation, "0.0") == 0) {
        ch->isZero = 1;
        ch->isValid = 1;
        return 0;
    }
    strncpy(ch->equation, equation, EQ_MAX_EQUATION_LEN - 1);
    ch->equation[EQ_MAX_EQUATION_LEN - 1] = '\0';
    trim(ch->equation);
    ch->amplitude = parse_amplitude(ch->equation);
    ch->frequency = parse_frequency(ch->equation, defaultFreq);
    ch->phaseOffset = parse_phase(ch->equation);
    ch->waveType = parse_wavetype(ch->equation);
    ch->isValid = 1;
    return 0;
}
References EqChannelData::amplitude, EQ_MAX_EQUATION_LEN, EQ_WAVE_SINE, EqChannelData::equation, EqChannelData::frequency, EqChannelData::isValid, EqChannelData::isZero, parse_amplitude(), parse_frequency(), parse_phase(), parse_wavetype(), EqChannelData::phaseOffset, EqChannelData::scaleFactor, trim(), and EqChannelData::waveType.
Referenced by eq_load_equations(), and eq_set_channel_equation().
eq_print_all()
void eq_print_all (const EqProcessor * proc)
Definition at line 350 of file equation_processor.cc.
{
    if (!proc) return;
    printf("\n=== Equation Processor ===\n");
    printf("Frequency: %.0f Hz, Rate: %u\n", proc->defaultFrequency, proc->sampleRate);
    printf("Channels: %d, Errors: %d\n\n", proc->channelCount, proc->parseErrors);
    for (int i = 0; i < proc->channelCount; i++) {
        const EqChannelData* ch = &proc->channels[i];
        printf("[%d] %s: amp=%.1f, freq=%.0f, phase=%.1f°\n",
               i, ch->id, ch->amplitude, ch->frequency, ch->phaseOffset * 180.0 / EQ_PI);
    }
    printf("==========================\n\n");
}
References EqChannelData::amplitude, EqProcessor::channelCount, EqProcessor::channels, EqProcessor::defaultFrequency, EQ_PI, EqChannelData::frequency, EqChannelData::id, EqProcessor::parseErrors, EqChannelData::phaseOffset, and EqProcessor::sampleRate.
eq_processor_init()
int eq_processor_init (EqProcessor * proc, double defaultFreq, uint32_t sampleRate)
Definition at line 153 of file equation_processor.cc.
{
    if (!proc) return -1;
    memset(proc, 0, sizeof(EqProcessor));
    proc->defaultFrequency = defaultFreq;
    proc->sampleRate = sampleRate;
    for (int i = 0; i < EQ_MAX_CHANNELS; i++) {
        proc->channels[i].frequency = defaultFreq;
        proc->channels[i].scaleFactor = 1000.0;
        proc->channels[i].isZero = 1;
    }
    return 0;
}
References EqProcessor::channels, EqProcessor::defaultFrequency, EQ_MAX_CHANNELS, EqChannelData::frequency, EqChannelData::isZero, EqProcessor::sampleRate, and EqChannelData::scaleFactor.
Referenced by eq_processor_reset().
eq_processor_reset()
void eq_processor_reset (EqProcessor * proc)
Definition at line 169 of file equation_processor.cc.
{
    if (!proc) return;
    double freq = proc->defaultFrequency;
    uint32_t rate = proc->sampleRate;
    eq_processor_init(proc, freq, rate);
}
References EqProcessor::defaultFrequency, eq_processor_init(), and EqProcessor::sampleRate.
Referenced by eq_load_equations().
eq_set_channel_equation()
int eq_set_channel_equation (EqProcessor * proc, const char * channelId, const char * equation)
Definition at line 251 of file equation_processor.cc.
{
    if (!proc || !channelId) return -1;
    int idx = -1;
    for (int i = 0; i < proc->channelCount; i++) {
        if (strcmp(proc->channels[i].id, channelId) == 0) { idx = i; break; }
    }
    if (idx < 0) {
        if (proc->channelCount >= EQ_MAX_CHANNELS) return -1;
        idx = proc->channelCount++;
        strncpy(proc->channels[idx].id, channelId, EQ_MAX_ID_LEN - 1);
    }
    return eq_parse_equation(equation, &proc->channels[idx], proc->defaultFrequency);
}
References EqProcessor::channelCount, EqProcessor::channels, EqProcessor::defaultFrequency, EQ_MAX_CHANNELS, EQ_MAX_ID_LEN, eq_parse_equation(), and EqChannelData::id.
eq_validate_equation()
int eq_validate_equation (const char * equation)
Definition at line 371 of file equation_processor.cc.
{
    if (!eq || !eq[0] || strcmp(eq, "0") == 0) return 1;
    if (find_ci(eq, "sin") || find_ci(eq, "cos") || find_ci(eq, "square") || find_ci(eq, "triangle")) return 1;
    char* endptr;
    strtod(eq, &endptr);
    return (*endptr == '\0' || isspace((unsigned char)*endptr));
}
References find_ci().