SV Publisher - Native C++ Module: BER Encoding Functions
BER Encoding Functions
Functions for encoding ASN.1 BER data.
Functions
size_t ber_encode_tag (uint8_t *buf, size_t buflen, uint8_t tag)
Encode a single-byte ASN.1 tag.
size_t ber_encode_length (uint8_t *buf, size_t buflen, size_t length)
Encode a BER length field.
size_t ber_encode_tlv (uint8_t *buf, size_t buflen, uint8_t tag, const uint8_t *value, size_t value_len)
Encode a complete TLV (Tag-Length-Value) structure.
size_t ber_encode_unsigned (uint8_t *buf, size_t buflen, uint8_t tag, uint64_t value)
Encode an unsigned integer.
size_t ber_encode_signed (uint8_t *buf, size_t buflen, uint8_t tag, int64_t value)
Encode a signed integer.
size_t ber_encode_int32_fixed (uint8_t *buf, size_t buflen, int32_t value)
Encode a 32-bit signed integer as fixed 4 bytes.
size_t ber_encode_uint32_fixed (uint8_t *buf, size_t buflen, uint32_t value)
Encode a 32-bit unsigned integer as fixed 4 bytes.
size_t ber_encode_visible_string (uint8_t *buf, size_t buflen, uint8_t tag, const char *str)
Encode a visible (ASCII) string.
size_t ber_encode_octet_string (uint8_t *buf, size_t buflen, uint8_t tag, const uint8_t *data, size_t data_len)
Encode an octet (byte) string.
size_t ber_encode_boolean (uint8_t *buf, size_t buflen, uint8_t tag, int value)
Encode a boolean value.
size_t ber_length_of_length (size_t length)
Calculate bytes needed to encode a BER length field.
Detailed Description
Functions for encoding ASN.1 BER data.
Function Documentation
ber_encode_boolean()
size_t ber_encode_boolean (uint8_t * buf, size_t buflen, uint8_t tag, int value)
Encode a boolean value.
Parameters
[out] buf Output buffer
[in] buflen Size of output buffer
[in] tag Tag byte
[in] value 0 for FALSE, non-zero for TRUE
Returns
Bytes written, or 0 on error
Definition at line 456 of file asn1_ber_encoder.cc.
{
    uint8_t bool_val = (value != 0) ? 0xFFU : 0x00U;
    return ber_encode_tlv(buf, buflen, tag, &bool_val, 1U);
}
References ber_encode_tlv().
ber_encode_int32_fixed()
size_t ber_encode_int32_fixed (uint8_t * buf, size_t buflen, int32_t value)
Encode a 32-bit signed integer as fixed 4 bytes.
Used for SV sample values which are always exactly 4 bytes (no TLV wrapper, just raw big-endian bytes).
Parameters
[out] buf Output buffer (must be at least 4 bytes)
[in] buflen Size of output buffer
[in] value Value to encode
Returns
4 on success, 0 if buffer too small
Definition at line 379 of file asn1_ber_encoder.cc.
{
    if (buflen < 4U) return 0U;
    buf[0] = (uint8_t)((value >> 24) & 0xFFU);
    buf[1] = (uint8_t)((value >> 16) & 0xFFU);
    buf[2] = (uint8_t)((value >> 8) & 0xFFU);
    buf[3] = (uint8_t)(value & 0xFFU);
    return 4U;
}
ber_encode_length()
size_t ber_encode_length (uint8_t * buf, size_t buflen, size_t length)
Encode a BER length field.
Encodes the length using BER definite-length encoding:
Short form (1 byte) for length < 128
Long form (2-5 bytes) for larger lengths
Parameters
[out] buf Output buffer
[in] buflen Size of output buffer
[in] length Length value to encode
Returns
Number of bytes written, or 0 if buffer too small
Definition at line 226 of file asn1_ber_encoder.cc.
{
    if (length < 128U) {
        if (buflen < 1U) return 0U;
        buf[0] = (uint8_t)length;
        return 1U;
    } else if (length <= 0xFFU) {
        if (buflen < 2U) return 0U;
        buf[0] = 0x81U;
        buf[1] = (uint8_t)length;
        return 2U;
    } else if (length <= 0xFFFFU) {
        if (buflen < 3U) return 0U;
        buf[0] = 0x82U;
        buf[1] = (uint8_t)(length >> 8);
        buf[2] = (uint8_t)(length & 0xFFU);
        return 3U;
    } else if (length <= 0xFFFFFFU) {
        if (buflen < 4U) return 0U;
        buf[0] = 0x83U;
        buf[1] = (uint8_t)(length >> 16);
        buf[2] = (uint8_t)((length >> 8) & 0xFFU);
        buf[3] = (uint8_t)(length & 0xFFU);
        return 4U;
    } else {
        if (buflen < 5U) return 0U;
        buf[0] = 0x84U;
        buf[1] = (uint8_t)(length >> 24);
        buf[2] = (uint8_t)((length >> 16) & 0xFFU);
        buf[3] = (uint8_t)((length >> 8) & 0xFFU);
        buf[4] = (uint8_t)(length & 0xFFU);
        return 5U;
    }
}
Referenced by ber_encode_tlv().
ber_encode_octet_string()
size_t ber_encode_octet_string (uint8_t * buf, size_t buflen, uint8_t tag, const uint8_t * data, size_t data_len)
Encode an octet (byte) string.
Parameters
[out] buf Output buffer
[in] buflen Size of output buffer
[in] tag Tag byte
[in] data Byte data
[in] data_len Length of data
Returns
Bytes written, or 0 on error
Definition at line 441 of file asn1_ber_encoder.cc.
{
    return ber_encode_tlv(buf, buflen, tag, data, data_len);
}
References ber_encode_tlv().
ber_encode_signed()
size_t ber_encode_signed (uint8_t * buf, size_t buflen, uint8_t tag, int64_t value)
Encode a signed integer.
Parameters
[out] buf Output buffer
[in] buflen Size of output buffer
[in] tag Tag byte
[in] value Signed value to encode
Returns
Bytes written, or 0 if buffer too small
Definition at line 343 of file asn1_ber_encoder.cc.
{
    uint8_t temp[8];
    size_t len = 0U;
    if (value >= 0) {
        return ber_encode_unsigned(buf, buflen, tag, (uint64_t)value);
    } else {
        int64_t v = value;
        size_t nbytes = 1U;
        while (nbytes < 8U) {
            int64_t min_val = -((int64_t)1 << (nbytes * 8U - 1U));
            if (v >= min_val) break;
            nbytes++;
        }
        for (size_t i = nbytes; i > 0U; i--) {
            temp[len++] = (uint8_t)(v >> ((i - 1U) * 8U));
        }
    }
    return ber_encode_tlv(buf, buflen, tag, temp, len);
}
References ber_encode_tlv(), and ber_encode_unsigned().
ber_encode_tag()
size_t ber_encode_tag (uint8_t * buf, size_t buflen, uint8_t tag)
Encode a single-byte ASN.1 tag.
Parameters
[out] buf Output buffer
[in] buflen Size of output buffer
[in] tag Tag value to encode (e.g., SV_TAG_SVID)
Returns
Number of bytes written (1), or 0 if buffer too small
Definition at line 205 of file asn1_ber_encoder.cc.
{
    if (buflen < 1U) {
        return 0U;
    }
    buf[0] = tag;
    return 1U;
}
Referenced by ber_encode_tlv().
ber_encode_tlv()
size_t ber_encode_tlv (uint8_t * buf, size_t buflen, uint8_t tag, const uint8_t * value, size_t value_len)
Encode a complete TLV (Tag-Length-Value) structure.
This is the core encoding function that combines tag, length, and value.
Parameters
[out] buf Output buffer
[in] buflen Size of output buffer
[in] tag Tag byte
[in] value Value data (can be NULL if value_len is 0)
[in] value_len Length of value data
Returns
Total bytes written, or 0 if buffer too small
Definition at line 273 of file asn1_ber_encoder.cc.
{
    size_t tag_len = 1U;
    size_t len_len = ber_length_of_length(value_len);
    size_t total = tag_len + len_len + value_len;
    if (buflen < total) return 0U;
    size_t offset = 0U;
    offset += ber_encode_tag(buf + offset, buflen - offset, tag);
    offset += ber_encode_length(buf + offset, buflen - offset, value_len);
    if (value_len > 0U && value != NULL) {
        memcpy(buf + offset, value, value_len);
        offset += value_len;
    }
    return offset;
}
References ber_encode_length(), ber_encode_tag(), and ber_length_of_length().
Referenced by ber_encode_boolean(), ber_encode_octet_string(), ber_encode_signed(), ber_encode_unsigned(), and ber_encode_visible_string().
ber_encode_uint32_fixed()
size_t ber_encode_uint32_fixed (uint8_t * buf, size_t buflen, uint32_t value)
Encode a 32-bit unsigned integer as fixed 4 bytes.
Used for SV quality flags which are always exactly 4 bytes.
Parameters
[out] buf Output buffer (must be at least 4 bytes)
[in] buflen Size of output buffer
[in] value Value to encode
Returns
4 on success, 0 if buffer too small
Definition at line 401 of file asn1_ber_encoder.cc.
{
    if (buflen < 4U) return 0U;
    buf[0] = (uint8_t)((value >> 24) & 0xFFU);
    buf[1] = (uint8_t)((value >> 16) & 0xFFU);
    buf[2] = (uint8_t)((value >> 8) & 0xFFU);
    buf[3] = (uint8_t)(value & 0xFFU);
    return 4U;
}
ber_encode_unsigned()
size_t ber_encode_unsigned (uint8_t * buf, size_t buflen, uint8_t tag, uint64_t value)
Encode an unsigned integer.
Encodes using minimum bytes needed (BER DER rules).
Parameters
[out] buf Output buffer
[in] buflen Size of output buffer
[in] tag Tag byte
[in] value Unsigned value to encode
Returns
Bytes written, or 0 if buffer too small
Definition at line 305 of file asn1_ber_encoder.cc.
{
    uint8_t temp[9];
    size_t len = 0U;
    if (value == 0U) {
        temp[0] = 0x00U;
        len = 1U;
    } else {
        uint64_t v = value;
        size_t nbytes = 0U;
        while (v > 0U) {
            nbytes++;
            v >>= 8;
        }
        uint8_t msb = (uint8_t)(value >> ((nbytes - 1U) * 8U));
        if (msb & 0x80U) {
            temp[len++] = 0x00U;
        }
        for (size_t i = nbytes; i > 0U; i--) {
            temp[len++] = (uint8_t)(value >> ((i - 1U) * 8U));
        }
    }
    return ber_encode_tlv(buf, buflen, tag, temp, len);
}
References ber_encode_tlv().
Referenced by ber_encode_signed().
ber_encode_visible_string()
size_t ber_encode_visible_string (uint8_t * buf, size_t buflen, uint8_t tag, const char * str)
Encode a visible (ASCII) string.
Used for svID (stream identifier) encoding.
Parameters
[out] buf Output buffer
[in] buflen Size of output buffer
[in] tag Tag byte (typically SV_TAG_SVID)
[in] str NULL-terminated string
Returns
Bytes written, or 0 on error
Definition at line 424 of file asn1_ber_encoder.cc.
{
    if (str == NULL) return 0U;
    size_t str_len = strlen(str);
    return ber_encode_tlv(buf, buflen, tag, (const uint8_t *)str, str_len);
}
References ber_encode_tlv().
ber_length_of_length()
size_t ber_length_of_length (size_t length)
Calculate bytes needed to encode a BER length field.
BER uses variable-length encoding for the length field:
Length < 128: 1 byte (short form)
Length < 256: 2 bytes (0x81 + 1 byte)
Length < 65536: 3 bytes (0x82 + 2 bytes)
Parameters
length The length value to encode
Returns
Number of bytes needed (1-5)
size_t len_bytes = ber_length_of_length(200);  // Returns 2
Definition at line 182 of file asn1_ber_encoder.cc.
{
    if (length < 128U) {
        return 1U;
    } else if (length <= 0xFFU) {
        return 2U;
    } else if (length <= 0xFFFFU) {
        return 3U;
    } else if (length <= 0xFFFFFFU) {
        return 4U;
    } else {
        return 5U;
    }
}
Referenced by ber_encode_tlv().