SV Publisher - Native C++ Module: sv_stats.h File Reference
sv_stats.h File Reference
Transmission Statistics Module.
#include "sv_native.h"
Functions
void npcap_stats_reset (void)
Reset all statistics to zero.
void npcap_stats_session_start (void)
Start a new statistics session.
void npcap_stats_session_end (void)
End the current statistics session.
void npcap_stats_update_rates (void)
Update rate calculations (call periodically).
void npcap_stats_get (TransmitStats *stats)
Get current statistics.
uint64_t npcap_stats_get_duration_ms (void)
Get session duration in milliseconds.
void npcap_stats_format_rate (double bps, char *buf, size_t buflen)
Format a bit rate as human-readable string.
void npcap_stats_record_packet (size_t bytes)
Record a successful packet transmission.
void npcap_stats_record_failure (void)
Record a failed packet transmission.
uint64_t npcap_stats_get_time_ms (void)
Get current time in milliseconds.
Detailed Description
Transmission Statistics Module.
Thread-safe statistics tracking for SV publishing.
Definition in file sv_stats.h.
Function Documentation
npcap_stats_format_rate()
void npcap_stats_format_rate (double bps, char * buf, size_t buflen)
Format a bit rate as human-readable string.
Parameters
bps Bits per second
buf Output buffer
buflen Buffer size
Definition at line 103 of file sv_stats_impl.cc.
{
    if (bps >= 1e9)      snprintf(buf, buflen, "%.2f Gbps", bps / 1e9);
    else if (bps >= 1e6) snprintf(buf, buflen, "%.2f Mbps", bps / 1e6);
    else if (bps >= 1e3) snprintf(buf, buflen, "%.2f Kbps", bps / 1e3);
    else                 snprintf(buf, buflen, "%.0f bps", bps);
}
npcap_stats_get()
void npcap_stats_get (TransmitStats * stats)
Get current statistics.
Parameters
stats Output structure
Definition at line 84 of file sv_stats_impl.cc.
{
    std::lock_guard<std::mutex> lock(g_mutex);
    memcpy(stats, &g_stats, sizeof(TransmitStats));
}
References g_mutex, and g_stats.
npcap_stats_get_duration_ms()
uint64_t npcap_stats_get_duration_ms (void)
Get session duration in milliseconds.
Returns
Duration in ms
Definition at line 89 of file sv_stats_impl.cc.
{
    std::lock_guard<std::mutex> lock(g_mutex);
    if (g_stats.session_start_ms == 0) return 0;
    if (g_stats.session_active) {
        return npcap_stats_get_time_ms() - g_stats.session_start_ms;
    }
    if (g_stats.session_end_ms > 0) {
        return g_stats.session_end_ms - g_stats.session_start_ms;
    }
    return 0;
}
References g_mutex, g_stats, and npcap_stats_get_time_ms().
npcap_stats_get_time_ms()
uint64_t npcap_stats_get_time_ms (void)
Get current time in milliseconds.
Returns
Milliseconds since epoch
Definition at line 26 of file sv_stats_impl.cc.
{
    using namespace std::chrono;
    return duration_cast<milliseconds>(steady_clock::now().time_since_epoch()).count();
}
Referenced by SvController::checkDurationElapsed(), get_time_ms(), SvController::getRemainingSeconds(), npcap_stats_get_duration_ms(), npcap_stats_record_packet(), npcap_stats_session_end(), npcap_stats_session_start(), npcap_stats_update_rates(), SvController::startAll(), SvController::writerLoopBatch(), and SvController::writerLoopImmediate().
npcap_stats_record_failure()
void npcap_stats_record_failure (void)
Record a failed packet transmission.
Definition at line 124 of file sv_stats_impl.cc.
{
    std::lock_guard<std::mutex> lock(g_mutex);
    g_stats.packets_failed++;
}
References g_mutex, and g_stats.
Referenced by publisher_loop_immediate(), publisher_loop_single(), and SvController::writerLoopImmediate().
npcap_stats_record_packet()
void npcap_stats_record_packet (size_t bytes)
Record a successful packet transmission.
Parameters
bytes Number of bytes sent
Definition at line 110 of file sv_stats_impl.cc.
{
    std::lock_guard<std::mutex> lock(g_mutex);
    g_stats.packets_sent++;
    g_stats.bytes_sent += bytes;
    g_stats.rate_packets_sent++;
    g_stats.rate_bytes_sent += bytes;
    g_stats.last_packet_ms = npcap_stats_get_time_ms();
    if (g_stats.packets_sent > 0) {
        g_stats.avg_packet_size = (double)g_stats.bytes_sent / g_stats.packets_sent;
    }
}
References g_mutex, g_stats, and npcap_stats_get_time_ms().
Referenced by publisher_loop_batch(), publisher_loop_immediate(), publisher_loop_single(), SvController::writerLoopBatch(), and SvController::writerLoopImmediate().
npcap_stats_reset()
void npcap_stats_reset (void)
Reset all statistics to zero.
Definition at line 37 of file sv_stats_impl.cc.
{
    std::lock_guard<std::mutex> lock(g_mutex);
    memset(&g_stats, 0, sizeof(g_stats));
}
References g_mutex, and g_stats.
Referenced by publisher_loop_batch(), publisher_loop_immediate(), publisher_loop_single(), SvController::resetAll(), SvController::writerLoopBatch(), and SvController::writerLoopImmediate().
npcap_stats_session_end()
void npcap_stats_session_end (void)
End the current statistics session.
Definition at line 53 of file sv_stats_impl.cc.
{
    std::lock_guard<std::mutex> lock(g_mutex);
    g_stats.session_end_ms = npcap_stats_get_time_ms();
    g_stats.session_active = 0;
}
References g_mutex, g_stats, and npcap_stats_get_time_ms().
Referenced by publisher_loop_batch(), publisher_loop_immediate(), publisher_loop_single(), SvController::writerLoopBatch(), and SvController::writerLoopImmediate().
npcap_stats_session_start()
void npcap_stats_session_start (void)
Start a new statistics session.
Definition at line 42 of file sv_stats_impl.cc.
{
    std::lock_guard<std::mutex> lock(g_mutex);
    g_stats.session_start_ms = npcap_stats_get_time_ms();
    g_stats.session_end_ms = 0;
    g_stats.rate_window_start_ms = g_stats.session_start_ms;
    g_stats.rate_bytes_sent = 0;
    g_stats.rate_packets_sent = 0;
    g_stats.session_active = 1;
}
References g_mutex, g_stats, and npcap_stats_get_time_ms().
Referenced by publisher_loop_batch(), publisher_loop_immediate(), publisher_loop_single(), SvController::writerLoopBatch(), and SvController::writerLoopImmediate().
npcap_stats_update_rates()
void npcap_stats_update_rates (void)
Update rate calculations (call periodically).
Definition at line 60 of file sv_stats_impl.cc.
{
    std::lock_guard<std::mutex> lock(g_mutex);
    uint64_t now = npcap_stats_get_time_ms();
    uint64_t elapsed = now - g_stats.rate_window_start_ms;
    /* Update every 250ms */
    if (elapsed >= 250) {
        double seconds = elapsed / 1000.0;
        if (seconds > 0) {
            g_stats.current_bps = (g_stats.rate_bytes_sent * 8.0) / seconds;
            g_stats.current_pps = g_stats.rate_packets_sent / seconds;
            if (g_stats.current_bps > g_stats.peak_bps) g_stats.peak_bps = g_stats.current_bps;
            if (g_stats.current_pps > g_stats.peak_pps) g_stats.peak_pps = g_stats.current_pps;
        }
        /* Reset window */
        g_stats.rate_window_start_ms = now;
        g_stats.rate_bytes_sent = 0;
        g_stats.rate_packets_sent = 0;
    }
}
References g_mutex, g_stats, and npcap_stats_get_time_ms().