SV Publisher - Native C++ Module: sv_controller.cc File Reference
sv_controller.cc File Reference
Implementation of SharedBuffer + SvController + Multi-Publisher FFI.
#include "../include/sv_controller.h"
#include "../include/npcap_transmitter.h"
#include "../include/sv_stats.h"
#include <cstdio>
#include <cstring>
#include <chrono>
#include <cmath>
Functions
int npcap_publisher_is_running (void)
uint32_t sv_mp_add_publisher (void)
int sv_mp_remove_publisher (uint32_t id)
int sv_mp_remove_all_publishers (void)
uint32_t sv_mp_get_publisher_count (void)
int sv_mp_configure_publisher (uint32_t id, const char *svID, uint16_t appID, uint32_t confRev, uint8_t smpSynch, const uint8_t *srcMAC, const uint8_t *dstMAC, int vlanPriority, int vlanID, uint64_t sampleRate, double frequency, double voltageAmplitude, double currentAmplitude, uint8_t asduCount, uint8_t channelCount)
int sv_mp_set_publisher_equations (uint32_t id, const char *equations)
int sv_mp_start_all (void)
int sv_mp_stop_all (void)
int sv_mp_reset_all (void)
int sv_mp_is_running (void)
int sv_mp_set_send_mode (int mode)
int sv_mp_get_send_mode (void)
int sv_mp_set_duration (uint32_t seconds, int repeat, int infinite, uint32_t count)
uint32_t sv_mp_get_remaining_seconds (void)
uint32_t sv_mp_get_current_repeat_cycle (void)
int sv_mp_is_duration_complete (void)
const char * sv_mp_get_last_error (void)
void sv_mp_set_usb_pad_size (int bytes)
int sv_mp_get_usb_pad_size (void)
void sv_mp_set_usb_min_gap_us (int us)
int sv_mp_get_usb_min_gap_us (void)
Detailed Description
Implementation of SharedBuffer + SvController + Multi-Publisher FFI.
This is the core of the multi-publisher architecture:
SharedBuffer::buildFromPublishers()
Takes all publishers' internal buffers
Merges into one sorted, interleaved schedule
Staggered timestamps so packets interleave evenly
SvController
Creates/manages SvPublisherInstance objects
On startAll(): prebuild → merge → spawn writer thread
Writer thread iterates the SharedBuffer, sends via npcap
FFI functions (extern "C")
sv_mp_* functions for Rust/Tauri to call
Complete lifecycle: add → configure → set equations → start → stop
Architecture flow: UI → Tauri IPC → Rust FFI → sv_mp_* → SvController → SharedBuffer → npcap
Definition in file sv_controller.cc.
Function Documentation
npcap_publisher_is_running()
int npcap_publisher_is_running (void)
Definition at line 823 of file sv_native_refactored.cc.
{
    return g_running.load() ? 1 : 0;
}
References g_running.
Referenced by SvController::startAll().
sv_mp_add_publisher()
uint32_t sv_mp_add_publisher (void)
Definition at line 866 of file sv_controller.cc.
{
    return SvController::instance().addPublisher();
}
References SvController::addPublisher(), and SvController::instance().
sv_mp_configure_publisher()
int sv_mp_configure_publisher (uint32_t id, const char * svID, uint16_t appID, uint32_t confRev, uint8_t smpSynch, const uint8_t * srcMAC, const uint8_t * dstMAC, int vlanPriority, int vlanID, uint64_t sampleRate, double frequency, double voltageAmplitude, double currentAmplitude, uint8_t asduCount, uint8_t channelCount)
Definition at line 888 of file sv_controller.cc.
{
    PublisherConfig config = {};
    if (svID && strlen(svID) > 0)
        strncpy(config.svID, svID, sizeof(config.svID) - 1);
    else
        strncpy(config.svID, "MU01", sizeof(config.svID) - 1);
    config.appID        = appID;
    config.confRev      = confRev;
    config.smpSynch     = smpSynch;
    if (srcMAC) memcpy(config.srcMAC, srcMAC, 6);
    if (dstMAC) memcpy(config.dstMAC, dstMAC, 6);
    config.vlanPriority = vlanPriority;
    config.vlanID       = vlanID;
    config.sampleRate   = sampleRate;
    config.frequency    = frequency;
    config.voltageAmplitude = voltageAmplitude;
    config.currentAmplitude = currentAmplitude;
    config.asduCount    = asduCount;
    config.channelCount = channelCount;
    return SvController::instance().configurePublisher(id, config);
}
References PublisherConfig::appID, PublisherConfig::asduCount, PublisherConfig::channelCount, SvController::configurePublisher(), PublisherConfig::confRev, PublisherConfig::currentAmplitude, PublisherConfig::dstMAC, PublisherConfig::frequency, SvController::instance(), PublisherConfig::sampleRate, PublisherConfig::smpSynch, PublisherConfig::srcMAC, PublisherConfig::svID, PublisherConfig::vlanID, PublisherConfig::vlanPriority, and PublisherConfig::voltageAmplitude.
sv_mp_get_current_repeat_cycle()
uint32_t sv_mp_get_current_repeat_cycle (void)
Definition at line 980 of file sv_controller.cc.
{
    return SvController::instance().getCurrentRepeatCycle();
}
References SvController::getCurrentRepeatCycle(), and SvController::instance().
sv_mp_get_last_error()
const char * sv_mp_get_last_error (void)
Definition at line 990 of file sv_controller.cc.
{
    return SvController::instance().getLastError();
}
References SvController::getLastError(), and SvController::instance().
sv_mp_get_publisher_count()
uint32_t sv_mp_get_publisher_count (void)
Definition at line 881 of file sv_controller.cc.
{
    return SvController::instance().getPublisherCount();
}
References SvController::getPublisherCount(), and SvController::instance().
sv_mp_get_remaining_seconds()
uint32_t sv_mp_get_remaining_seconds (void)
Definition at line 975 of file sv_controller.cc.
{
    return SvController::instance().getRemainingSeconds();
}
References SvController::getRemainingSeconds(), and SvController::instance().
sv_mp_get_send_mode()
int sv_mp_get_send_mode (void)
Definition at line 963 of file sv_controller.cc.
{
    return SvController::instance().getSendMode();
}
References SvController::getSendMode(), and SvController::instance().
sv_mp_get_usb_min_gap_us()
int sv_mp_get_usb_min_gap_us (void)
Definition at line 1014 of file sv_controller.cc.
{
    return SvController::instance().getUsbMinGapUs();
}
References SvController::getUsbMinGapUs(), and SvController::instance().
sv_mp_get_usb_pad_size()
int sv_mp_get_usb_pad_size (void)
Definition at line 1002 of file sv_controller.cc.
{
    return SvController::instance().getUsbPadSize();
}
References SvController::getUsbPadSize(), and SvController::instance().
sv_mp_is_duration_complete()
int sv_mp_is_duration_complete (void)
Definition at line 985 of file sv_controller.cc.
{
    return SvController::instance().isDurationComplete() ? 1 : 0;
}
References SvController::instance(), and SvController::isDurationComplete().
sv_mp_is_running()
int sv_mp_is_running (void)
Definition at line 951 of file sv_controller.cc.
{
    return SvController::instance().isRunning() ? 1 : 0;
}
References SvController::instance(), and SvController::isRunning().
Referenced by npcap_publisher_start().
sv_mp_remove_all_publishers()
int sv_mp_remove_all_publishers (void)
Definition at line 876 of file sv_controller.cc.
{
    return SvController::instance().removeAllPublishers();
}
References SvController::instance(), and SvController::removeAllPublishers().
sv_mp_remove_publisher()
int sv_mp_remove_publisher (uint32_t id)
Definition at line 871 of file sv_controller.cc.
{
    return SvController::instance().removePublisher(id);
}
References SvController::instance(), and SvController::removePublisher().
sv_mp_reset_all()
int sv_mp_reset_all (void)
Definition at line 946 of file sv_controller.cc.
{
    return SvController::instance().resetAll();
}
References SvController::instance(), and SvController::resetAll().
sv_mp_set_duration()
int sv_mp_set_duration (uint32_t seconds, int repeat, int infinite, uint32_t count)
Definition at line 968 of file sv_controller.cc.
{
    return SvController::instance().setDuration(
        seconds, repeat != 0, infinite != 0, count);
}
References SvController::instance(), and SvController::setDuration().
sv_mp_set_publisher_equations()
int sv_mp_set_publisher_equations (uint32_t id, const char * equations)
Definition at line 929 of file sv_controller.cc.
{
    return SvController::instance().setPublisherEquations(id, equations);
}
References SvController::instance(), and SvController::setPublisherEquations().
sv_mp_set_send_mode()
int sv_mp_set_send_mode (int mode)
Definition at line 958 of file sv_controller.cc.
{
    return SvController::instance().setSendMode(mode);
}
References SvController::instance(), and SvController::setSendMode().
sv_mp_set_usb_min_gap_us()
void sv_mp_set_usb_min_gap_us (int us)
Definition at line 1007 of file sv_controller.cc.
{
    SvController::instance().setUsbMinGapUs(us);
    printf("[controller] USB min gap set to %d us\n",
           SvController::instance().getUsbMinGapUs());
}
References SvController::instance(), and SvController::setUsbMinGapUs().
sv_mp_set_usb_pad_size()
void sv_mp_set_usb_pad_size (int bytes)
Definition at line 995 of file sv_controller.cc.
{
    SvController::instance().setUsbPadSize(bytes);
    printf("[controller] USB pad size set to %d bytes\n",
           SvController::instance().getUsbPadSize());
}
References SvController::instance(), and SvController::setUsbPadSize().
sv_mp_start_all()
int sv_mp_start_all (void)
Definition at line 936 of file sv_controller.cc.
{
    return SvController::instance().startAll();
}
References SvController::instance(), and SvController::startAll().
sv_mp_stop_all()
int sv_mp_stop_all (void)
Definition at line 941 of file sv_controller.cc.
{
    return SvController::instance().stopAll();
}
References SvController::instance(), and SvController::stopAll().