SV Publisher - Native C++ Module: sv_encoder.h File Reference
sv_encoder.h File Reference
IEC 61850-9-2LE SV Packet Encoder.
#include <cstdint>
#include <cstddef>
Data Structures
struct SvEncoderConfig
Macros
#define SV_ETHERTYPE 0x88BA
#define SV_MAX_CHANNELS 20
#define SV_MAX_ASDU 8
#define SV_MAX_SVID_LEN 64
#define SV_MIN_FRAME_SIZE 60
#define SV_MAX_FRAME_SIZE 1500
Typedefs
typedef struct SvEncoderConfig SvEncoderConfig
Functions
void sv_encoder_set_config (const SvEncoderConfig *config)
Set encoder configuration.
void sv_encoder_get_config (SvEncoderConfig *config)
Get current encoder configuration.
int sv_encoder_encode_packet (uint32_t smpCnt, const int32_t *samples, uint8_t *outBuffer, size_t *outSize)
Encode a single SV packet.
int sv_encoder_encode_multi_asdu (uint32_t baseSmpCnt, const int32_t **samplesArray, uint8_t *outBuffer, size_t *outSize)
Encode packet with multiple ASDUs.
size_t sv_encoder_get_frame_size (void)
Get expected frame size for current config.
Detailed Description
IEC 61850-9-2LE SV Packet Encoder.
Encodes Sampled Values packets according to IEC 61850-9-2LE standard.
Definition in file sv_encoder.h.
Macro Definition Documentation
SV_ETHERTYPE
#define SV_ETHERTYPE 0x88BA
Definition at line 22 of file sv_encoder.h.
SV_MAX_ASDU
#define SV_MAX_ASDU 8
Definition at line 24 of file sv_encoder.h.
SV_MAX_CHANNELS
#define SV_MAX_CHANNELS 20
Definition at line 23 of file sv_encoder.h.
Referenced by SvPublisherInstance::configure(), npcap_get_sample_frame(), npcap_publisher_configure(), prebuild_frames(), SvPublisherInstance::prebuildFrames(), publisher_loop_single(), and sv_encoder_set_config().
SV_MAX_FRAME_SIZE
#define SV_MAX_FRAME_SIZE 1500
Definition at line 27 of file sv_encoder.h.
Referenced by SvPublisherInstance::allocFrameCache(), and SvPublisherInstance::prebuildFrames().
SV_MAX_SVID_LEN
#define SV_MAX_SVID_LEN 64
Definition at line 25 of file sv_encoder.h.
SV_MIN_FRAME_SIZE
#define SV_MIN_FRAME_SIZE 60
Definition at line 26 of file sv_encoder.h.
Typedef Documentation
SvEncoderConfig
typedef struct SvEncoderConfig SvEncoderConfig
Function Documentation
sv_encoder_encode_multi_asdu()
int sv_encoder_encode_multi_asdu (uint32_t baseSmpCnt, const int32_t ** samplesArray, uint8_t * outBuffer, size_t * outSize)
Encode packet with multiple ASDUs.
Parameters
baseSmpCnt Base sample counter for first ASDU
samplesArray Array of sample arrays (asduCount × 8 values)
outBuffer Output buffer
outSize Output: actual encoded size
Returns
0 on success, -1 on error
Definition at line 215 of file sv_encoder_impl.cc.
  {
    if (!buffer || !outSize || !samplesArray) return -1;
    std::lock_guard<std::mutex> lock(g_mutex);
    size_t pos = 0;
    uint8_t asduCount = g_config.asduCount;
    /* Ethernet Header */
    memcpy(buffer + pos, g_config.dstMAC, 6); pos += 6;
    memcpy(buffer + pos, g_config.srcMAC, 6); pos += 6;
    /* Optional VLAN Tag */
    if (g_config.vlanID > 0) {
        buffer[pos++] = 0x81;
        buffer[pos++] = 0x00;
        uint16_t vlanTag = ((g_config.vlanPriority & 0x7) << 13) | (g_config.vlanID & 0xFFF);
        buffer[pos++] = (vlanTag >> 8) & 0xFF;
        buffer[pos++] = vlanTag & 0xFF;
    }
    /* EtherType: SV */
    buffer[pos++] = 0x88;
    buffer[pos++] = 0xBA;
    /* APPID */
    buffer[pos++] = (g_config.appID >> 8) & 0xFF;
    buffer[pos++] = g_config.appID & 0xFF;
    /* Length placeholder */
    size_t lengthPos = pos;
    buffer[pos++] = 0;
    buffer[pos++] = 0;
    /* Reserved */
    buffer[pos++] = 0; buffer[pos++] = 0;
    buffer[pos++] = 0; buffer[pos++] = 0;
    /* savPdu with 2-byte length (for larger payloads) */
    buffer[pos++] = 0x60;
    size_t savPduLenPos = pos;
    buffer[pos++] = 0x82;  /* 2-byte length follows */
    buffer[pos++] = 0;
    buffer[pos++] = 0;
    /* noASDU */
    buffer[pos++] = 0x80;
    buffer[pos++] = 0x01;
    buffer[pos++] = asduCount;
    /* seqASDU with 2-byte length */
    buffer[pos++] = 0xA2;
    size_t seqASDULenPos = pos;
    buffer[pos++] = 0x82;
    buffer[pos++] = 0;
    buffer[pos++] = 0;
    /* Encode each ASDU */
    for (int i = 0; i < asduCount; i++) {
        buffer[pos++] = 0x30;  /* SEQUENCE */
        size_t asduLenPos = pos;
        buffer[pos++] = 0;
        /* svID */
        size_t svIDLen = strlen(g_config.svID);
        if (svIDLen == 0) {
            buffer[pos++] = 0x80;
            buffer[pos++] = 0x04;
            memcpy(buffer + pos, "MU01", 4); pos += 4;
        } else {
            buffer[pos++] = 0x80;
            buffer[pos++] = (uint8_t)svIDLen;
            memcpy(buffer + pos, g_config.svID, svIDLen); pos += svIDLen;
        }
        /* smpCnt */
        uint16_t smpCnt = (uint16_t)(baseSmpCnt + i);
        buffer[pos++] = 0x82;
        buffer[pos++] = 0x02;
        buffer[pos++] = (smpCnt >> 8) & 0xFF;
        buffer[pos++] = smpCnt & 0xFF;
        /* confRev */
        buffer[pos++] = 0x83;
        buffer[pos++] = 0x04;
        buffer[pos++] = (g_config.confRev >> 24) & 0xFF;
        buffer[pos++] = (g_config.confRev >> 16) & 0xFF;
        buffer[pos++] = (g_config.confRev >> 8) & 0xFF;
        buffer[pos++] = g_config.confRev & 0xFF;
        /* smpSynch */
        buffer[pos++] = 0x85;
        buffer[pos++] = 0x01;
        buffer[pos++] = g_config.smpSynch;
        /* seqData (dynamic channels) */
        uint8_t channelCount = g_config.channelCount;
        uint8_t seqDataLen = channelCount * 8;
        buffer[pos++] = 0x87;
        buffer[pos++] = seqDataLen;
        const int32_t* samples = samplesArray[i];
        for (int ch = 0; ch < channelCount; ch++) {
            int32_t val = samples[ch];
            buffer[pos++] = (val >> 24) & 0xFF;
            buffer[pos++] = (val >> 16) & 0xFF;
            buffer[pos++] = (val >> 8) & 0xFF;
            buffer[pos++] = val & 0xFF;
            buffer[pos++] = 0x00;
            buffer[pos++] = 0x00;
            buffer[pos++] = 0x00;
            buffer[pos++] = 0x00;
        }
        buffer[asduLenPos] = (uint8_t)(pos - asduLenPos - 1);
    }
    /* Fill seqASDU length (2-byte) */
    size_t seqASDULen = pos - seqASDULenPos - 3;
    buffer[seqASDULenPos + 1] = (seqASDULen >> 8) & 0xFF;
    buffer[seqASDULenPos + 2] = seqASDULen & 0xFF;
    /* Fill savPdu length (2-byte) */
    size_t savPduLen = pos - savPduLenPos - 3;
    buffer[savPduLenPos + 1] = (savPduLen >> 8) & 0xFF;
    buffer[savPduLenPos + 2] = savPduLen & 0xFF;
    /* APDU Length: savPduLen + 12 (matches Node.js formula for multi-ASDU) */
    size_t apduLen = savPduLen + 12;
    buffer[lengthPos] = (apduLen >> 8) & 0xFF;
    buffer[lengthPos + 1] = apduLen & 0xFF;
    /* Pad to minimum frame size */
    while (pos < 60) buffer[pos++] = 0;
    *outSize = pos;
    return 0;
}
References g_config, and g_mutex.
sv_encoder_encode_packet()
int sv_encoder_encode_packet (uint32_t smpCnt, const int32_t * samples, uint8_t * outBuffer, size_t * outSize)
Encode a single SV packet.
Parameters
smpCnt Sample counter
samples Array of 8 channel values (int32_t)
outBuffer Output buffer (must be at least SV_MAX_FRAME_SIZE bytes)
outSize Output: actual encoded size
Returns
0 on success, -1 on error
Definition at line 65 of file sv_encoder_impl.cc.
  {
    if (!buffer || !outSize || !samples) return -1;
    std::lock_guard<std::mutex> lock(g_mutex);
    size_t pos = 0;
    /* Ethernet Header */
    memcpy(buffer + pos, g_config.dstMAC, 6); pos += 6;
    memcpy(buffer + pos, g_config.srcMAC, 6); pos += 6;
    /* Optional VLAN Tag (802.1Q) */
    if (g_config.vlanID > 0) {
        buffer[pos++] = 0x81;
        buffer[pos++] = 0x00;
        uint16_t vlanTag = ((g_config.vlanPriority & 0x7) << 13) | (g_config.vlanID & 0xFFF);
        buffer[pos++] = (vlanTag >> 8) & 0xFF;
        buffer[pos++] = vlanTag & 0xFF;
    }
    /* EtherType: SV (0x88BA) */
    buffer[pos++] = 0x88;
    buffer[pos++] = 0xBA;
    /* APPID */
    buffer[pos++] = (g_config.appID >> 8) & 0xFF;
    buffer[pos++] = g_config.appID & 0xFF;
    /* Length placeholder */
    size_t lengthPos = pos;
    buffer[pos++] = 0;
    buffer[pos++] = 0;
    /* Reserved (4 bytes) */
    buffer[pos++] = 0; buffer[pos++] = 0;
    buffer[pos++] = 0; buffer[pos++] = 0;
    /* savPdu (ASN.1 tag 0x60 = APPLICATION 0) */
    buffer[pos++] = 0x60;
    size_t savPduLenPos = pos;
    buffer[pos++] = 0;  /* Length placeholder */
    /* noASDU (tag 0x80 = context [0]) */
    buffer[pos++] = 0x80;
    buffer[pos++] = 0x01;
    buffer[pos++] = 0x01;  /* 1 ASDU */
    /* seqASDU (tag 0xA2 = context [2] constructed) */
    buffer[pos++] = 0xA2;
    size_t seqASDULenPos = pos;
    buffer[pos++] = 0;  /* Length placeholder */
    /* ASDU (tag 0x30 = SEQUENCE) */
    buffer[pos++] = 0x30;
    size_t asduLenPos = pos;
    buffer[pos++] = 0;  /* Length placeholder */
    /* svID (tag 0x80 = context [0]) */
    size_t svIDLen = strlen(g_config.svID);
    if (svIDLen == 0) {
        /* Fallback to default if empty */
        buffer[pos++] = 0x80;
        buffer[pos++] = 0x04;
        memcpy(buffer + pos, "MU01", 4); pos += 4;
        svIDLen = 4;
    } else {
        buffer[pos++] = 0x80;
        buffer[pos++] = (uint8_t)svIDLen;
        memcpy(buffer + pos, g_config.svID, svIDLen); pos += svIDLen;
    }
    /* smpCnt (tag 0x82 = context [2]) */
    buffer[pos++] = 0x82;
    buffer[pos++] = 0x02;
    buffer[pos++] = (smpCnt >> 8) & 0xFF;
    buffer[pos++] = smpCnt & 0xFF;
    /* confRev (tag 0x83 = context [3]) */
    buffer[pos++] = 0x83;
    buffer[pos++] = 0x04;
    buffer[pos++] = (g_config.confRev >> 24) & 0xFF;
    buffer[pos++] = (g_config.confRev >> 16) & 0xFF;
    buffer[pos++] = (g_config.confRev >> 8) & 0xFF;
    buffer[pos++] = g_config.confRev & 0xFF;
    /* smpSynch (tag 0x85 = context [5]) */
    buffer[pos++] = 0x85;
    buffer[pos++] = 0x01;
    buffer[pos++] = g_config.smpSynch;
    /* seqData (tag 0x87 = context [7])
     * Dynamic channels: channelCount × (4 bytes value + 4 bytes quality) */
    uint8_t channelCount = g_config.channelCount;
    uint8_t seqDataLen = channelCount * 8;  // 8 bytes per channel
    buffer[pos++] = 0x87;
    buffer[pos++] = seqDataLen;
    for (int i = 0; i < channelCount; i++) {
        int32_t val = samples[i];
        /* Value (big-endian) */
        buffer[pos++] = (val >> 24) & 0xFF;
        buffer[pos++] = (val >> 16) & 0xFF;
        buffer[pos++] = (val >> 8) & 0xFF;
        buffer[pos++] = val & 0xFF;
        /* Quality (0x0000 = Good) */
        buffer[pos++] = 0x00;
        buffer[pos++] = 0x00;
        buffer[pos++] = 0x00;
        buffer[pos++] = 0x00;
    }
    /* Fill in lengths */
    size_t asduLen = pos - asduLenPos - 1;
    buffer[asduLenPos] = (uint8_t)asduLen;
    size_t seqASDULen = pos - seqASDULenPos - 1;
    buffer[seqASDULenPos] = (uint8_t)seqASDULen;
    size_t savPduLen = pos - savPduLenPos - 1;
    buffer[savPduLenPos] = (uint8_t)savPduLen;
    /* APDU Length: savPduLen + 10 (matches Node.js working formula) */
    size_t apduLen = savPduLen + 10;
    buffer[lengthPos] = (apduLen >> 8) & 0xFF;
    buffer[lengthPos + 1] = apduLen & 0xFF;
    /* Debug output (first packet only) */
    if (!g_debug_printed) {
        printf("[encoder] First packet: svID=%zu bytes, channels=%d, ASDU=%zu, APDU=%zu\n",
               svIDLen, channelCount, asduLen, apduLen);
        g_debug_printed = true;
    }
    /* Pad to minimum Ethernet frame (60 bytes) */
    while (pos < 60) buffer[pos++] = 0;
    *outSize = pos;
    return 0;
}
References g_config, g_debug_printed, and g_mutex.
Referenced by npcap_get_sample_frame(), prebuild_frames(), SvPublisherInstance::prebuildFrames(), and publisher_loop_single().
sv_encoder_get_config()
void sv_encoder_get_config (SvEncoderConfig * config)
Get current encoder configuration.
Definition at line 54 of file sv_encoder_impl.cc.
{
    std::lock_guard<std::mutex> lock(g_mutex);
    memcpy(config, &g_config, sizeof(SvEncoderConfig));
}
References g_config, and g_mutex.
sv_encoder_get_frame_size()
size_t sv_encoder_get_frame_size (void)
Get expected frame size for current config.
Definition at line 362 of file sv_encoder_impl.cc.
{
    std::lock_guard<std::mutex> lock(g_mutex);
    size_t headerSize = 14 + (g_config.vlanID > 0 ? 4 : 0);
    size_t svHeaderSize = 8;
    size_t savPduOverhead = 10;
    size_t svIDLen = strlen(g_config.svID);
    size_t seqDataSize = 2 + (g_config.channelCount * 8);  // 2 bytes TL + channels * 8
    size_t asduSize = 2 + svIDLen + 4 + 6 + 3 + seqDataSize;  /* svID+smpCnt+confRev+smpSynch+seqData */
    size_t total = headerSize + svHeaderSize + savPduOverhead + (asduSize * g_config.asduCount);
    return total < 60 ? 60 : total;
}
References g_config, and g_mutex.
sv_encoder_set_config()
void sv_encoder_set_config (const SvEncoderConfig * config)
Set encoder configuration.
Definition at line 39 of file sv_encoder_impl.cc.
{
    std::lock_guard<std::mutex> lock(g_mutex);
    memcpy(&g_config, config, sizeof(SvEncoderConfig));
    g_config.svID[sizeof(g_config.svID) - 1] = '\0';
    // Validate channel count (1-20)
    if (g_config.channelCount < 1 || g_config.channelCount > SV_MAX_CHANNELS) {
        g_config.channelCount = 8;  // Default to 8
    }
    g_debug_printed = false;
    printf("[encoder] Config: svID='%s', appID=0x%04X, ASDUs=%d, channels=%d\n",
           config->svID, config->appID, config->asduCount, g_config.channelCount);
}
References SvEncoderConfig::appID, SvEncoderConfig::asduCount, g_config, g_debug_printed, g_mutex, SV_MAX_CHANNELS, and SvEncoderConfig::svID.
Referenced by npcap_get_sample_frame(), prebuild_frames(), SvPublisherInstance::prebuildFrames(), and publisher_loop_single().