SV Publisher - Native C++ Module: sv_publisher.h File Reference
sv_publisher.h File Reference
SV Publisher Module Header.
#include <stdint.h>
#include <stddef.h>
Functions
int npcap_publisher_configure (const char *svID, uint16_t appID, uint32_t confRev, uint8_t smpSynch, const uint8_t *srcMAC, const uint8_t *dstMAC, int vlanPriority, int vlanID, uint64_t sampleRate, double frequency, double voltageAmplitude, double currentAmplitude, uint8_t asduCount)
Configure the publisher.
int npcap_publisher_start (void)
Start publishing.
int npcap_publisher_stop (void)
Stop publishing.
int npcap_publisher_is_running (void)
Check if publisher is running.
int npcap_set_duration_mode (uint32_t durationSeconds, int repeatEnabled, int repeatInfinite, uint32_t repeatCount)
Set duration and repeat mode.
uint32_t npcap_get_remaining_seconds (void)
Get remaining seconds in current cycle.
uint32_t npcap_get_current_repeat_cycle (void)
Get current repeat cycle number.
int npcap_is_duration_complete (void)
Check if duration has completed.
int npcap_set_equations (const char *equations)
Set channel equations Format: "id1:equation1|id2:equation2|...".
int npcap_get_sample_frame (uint8_t *outBuffer, size_t bufferSize, size_t *outFrameSize, uint32_t smpCnt)
Get a sample frame with specified smpCnt.
int npcap_get_current_channel_values (int32_t *outValues)
Get current channel values.
uint32_t npcap_get_current_smp_cnt (void)
Get current sample count.
Detailed Description
SV Publisher Module Header.
High-level publisher functions for SV packet transmission. Combines encoder, transmitter, and statistics modules.
Definition in file sv_publisher.h.
Function Documentation
npcap_get_current_channel_values()
int npcap_get_current_channel_values (int32_t * outValues)
Get current channel values.
Parameters
outValues Array of 8 int32_t
Returns
0 on success
Get current channel values.
Parameters
outValues - Array to receive 8 channel values (must be int32_t[8])
Returns
0 on success, -1 on error
Definition at line 907 of file sv_native_refactored.cc.
{
    if (!outValues) return -1;
    std::lock_guard<std::mutex> lock(g_channel_mutex);
    memcpy(outValues, g_channel_values, g_config.channelCount * sizeof(int32_t));
    return (int)g_config.channelCount;  // Return channel count
}
References g_channel_mutex, g_channel_values, and g_config.
npcap_get_current_repeat_cycle()
uint32_t npcap_get_current_repeat_cycle (void)
Get current repeat cycle number.
Returns
Cycle number (0-based)
Current cycle (0-based)
Definition at line 848 of file sv_native_refactored.cc.
{
    return g_repeat_cycle.load();
}
References g_repeat_cycle.
npcap_get_current_smp_cnt()
uint32_t npcap_get_current_smp_cnt (void)
Get current sample count.
Returns
Current smpCnt
Current sample count value
Definition at line 915 of file sv_native_refactored.cc.
{
    return g_current_smp_cnt.load();
}
References g_current_smp_cnt.
npcap_get_remaining_seconds()
uint32_t npcap_get_remaining_seconds (void)
Get remaining seconds in current cycle.
Returns
Remaining seconds
Get remaining seconds in current cycle.
Returns
Remaining seconds (0 if continuous mode or complete)
Definition at line 839 of file sv_native_refactored.cc.
{
    if (g_config.durationSeconds == 0 || !g_running.load()) return g_config.durationSeconds;
    uint64_t elapsed = get_time_ms() - g_start_time_ms.load();
    uint64_t duration = (uint64_t)g_config.durationSeconds * 1000ULL;
    return (elapsed >= duration) ? 0 : (uint32_t)((duration - elapsed) / 1000);
}
References g_config, g_running, g_start_time_ms, and get_time_ms().
npcap_get_sample_frame()
int npcap_get_sample_frame (uint8_t * outBuffer, size_t bufferSize, size_t * outFrameSize, uint32_t smpCnt)
Get a sample frame with specified smpCnt.
Parameters
outBuffer Output buffer
bufferSize Buffer size
outFrameSize Output: actual frame size
smpCnt Sample count value
Returns
0 on success
Get a sample frame with specified smpCnt.
Parameters
outBuffer - Buffer to receive frame bytes (should be at least 256 bytes)
bufferSize - Size of the output buffer
outFrameSize - Actual frame size written
smpCnt - Sample count to use (0 for current)
Returns
0 on success, -1 on error
Definition at line 869 of file sv_native_refactored.cc.
{
    if (!outBuffer || !outFrameSize || bufferSize < 64) return -1;
    SvEncoderConfig enc;
    {
        std::lock_guard<std::mutex> lock(g_mutex);
        strncpy(enc.svID, g_config.svID, sizeof(enc.svID) - 1);
        enc.appID = g_config.appID;
        enc.confRev = g_config.confRev;
        enc.smpSynch = g_config.smpSynch;
        memcpy(enc.srcMAC, g_config.srcMAC, 6);
        memcpy(enc.dstMAC, g_config.dstMAC, 6);
        enc.vlanPriority = g_config.vlanPriority;
        enc.vlanID = g_config.vlanID;
        enc.asduCount = 1;
        enc.channelCount = g_config.channelCount;
    }
    sv_encoder_set_config(&enc);
    int32_t samples[SV_MAX_CHANNELS] = {0};  // Support up to 20 channels
    double t = (double)smpCnt / (double)g_config.sampleRate;
    {
        std::lock_guard<std::mutex> lock(g_eq_mutex);
        g_eq_processor.generate9_2LESamples(t, samples, g_config.channelCount);
    }
    *outFrameSize = bufferSize;
    int result = sv_encoder_encode_packet(smpCnt, samples, outBuffer, outFrameSize);
    g_current_smp_cnt.store(smpCnt);
    {
        std::lock_guard<std::mutex> lock(g_channel_mutex);
        memcpy(g_channel_values, samples, g_config.channelCount * sizeof(int32_t));
    }
    return result;
}
References SvEncoderConfig::appID, SvEncoderConfig::asduCount, SvEncoderConfig::channelCount, SvEncoderConfig::confRev, SvEncoderConfig::dstMAC, g_channel_mutex, g_channel_values, g_config, g_current_smp_cnt, g_eq_mutex, g_eq_processor(), g_mutex, SvEncoderConfig::smpSynch, SvEncoderConfig::srcMAC, sv_encoder_encode_packet(), sv_encoder_set_config(), SV_MAX_CHANNELS, SvEncoderConfig::svID, SvEncoderConfig::vlanID, and SvEncoderConfig::vlanPriority.
npcap_is_duration_complete()
int npcap_is_duration_complete (void)
Check if duration has completed.
Returns
1 if complete, 0 if running
1 if complete, 0 if still running
Definition at line 852 of file sv_native_refactored.cc.
{
    return g_duration_complete.load() ? 1 : 0;
}
References g_duration_complete.
npcap_publisher_configure()
int npcap_publisher_configure (const char * svID, uint16_t appID, uint32_t confRev, uint8_t smpSynch, const uint8_t * srcMAC, const uint8_t * dstMAC, int vlanPriority, int vlanID, uint64_t sampleRate, double frequency, double voltageAmplitude, double currentAmplitude, uint8_t asduCount)
Configure the publisher.
Parameters
svID Stream identifier
appID Application ID
confRev Configuration revision
smpSynch Synchronization status
srcMAC Source MAC address (6 bytes)
dstMAC Destination MAC address (6 bytes)
vlanPriority VLAN priority (0-7)
vlanID VLAN ID (0 = no VLAN)
sampleRate Sample rate in Hz
frequency Power frequency (50 or 60 Hz)
voltageAmplitude Voltage amplitude
currentAmplitude Current amplitude
asduCount Number of ASDUs per frame (1, 4, or 8)
Returns
0 on success
npcap_publisher_is_running()
int npcap_publisher_is_running (void)
Check if publisher is running.
Returns
1 if running, 0 if not
Definition at line 823 of file sv_native_refactored.cc.
{
    return g_running.load() ? 1 : 0;
}
npcap_publisher_start()
int npcap_publisher_start (void)
Start publishing.
Returns
0 on success
Definition at line 753 of file sv_native_refactored.cc.
{
    if (!npcap_is_open()) {
        snprintf(g_error_buffer, sizeof(g_error_buffer), "No interface open");
        return -1;
    }
    if (g_running.load()) return 0;
    if (sv_mp_is_running()) {
        snprintf(g_error_buffer, sizeof(g_error_buffer),
                 "Multi-publisher is already running. Stop it before using single-publisher.");
        return -1;
    }
    g_start_time_ms.store(get_time_ms());
    g_duration_complete.store(false);
    g_running.store(true);
    /* Dispatch based on configured send mode */
    switch (g_config.sendMode) {
        case SEND_MODE_QUEUE:
            /* Force SendQueue (batch) mode */
            if (npcap_sendqueue_available()) {
                printf("[publisher] Mode: FORCED SendQueue (batch)\n");
                g_thread = std::thread(publisher_loop_batch);
            } else {
                printf("[publisher] WARNING: SendQueue requested but not available, falling back to single\n");
                g_thread = std::thread(publisher_loop_single);
            }
            break;
        case SEND_MODE_PACKET:
            /* Force SendPacket (immediate) mode */
            printf("[publisher] Mode: FORCED SendPacket (immediate)\n");
            g_thread = std::thread(publisher_loop_immediate);
            break;
        case SEND_MODE_USB:
            /* USB-Optimized: immediate + forced SPIN + minimum gap */
            printf("[publisher] Mode: USB-OPTIMIZED (spin pacing + min gap)\n");
            g_thread = std::thread(publisher_loop_immediate);
            break;
        case SEND_MODE_AUTO:
        default:
            /* Auto-detect: use SendQueue if available, else fall back to single */
            if (npcap_sendqueue_available()) {
                printf("[publisher] Mode: AUTO -> SendQueue (batch)\n");
                g_thread = std::thread(publisher_loop_batch);
            } else {
                printf("[publisher] Mode: AUTO -> single (no sendqueue)\n");
                g_thread = std::thread(publisher_loop_single);
            }
            break;
    }
    return 0;
}
References g_config, g_duration_complete, g_error_buffer, g_running, g_start_time_ms, g_thread, get_time_ms(), npcap_is_open(), npcap_sendqueue_available(), publisher_loop_batch(), publisher_loop_immediate(), publisher_loop_single(), SEND_MODE_AUTO, SEND_MODE_PACKET, SEND_MODE_QUEUE, SEND_MODE_USB, and sv_mp_is_running().
npcap_publisher_stop()
int npcap_publisher_stop (void)
Stop publishing.
Returns
0 on success
Definition at line 812 of file sv_native_refactored.cc.
{
    if (!g_running.load()) return 0;
    g_running.store(false);
    if (g_thread.joinable()) g_thread.join();
    free_frame_cache();
    return 0;
}
References free_frame_cache(), g_running, and g_thread.
Referenced by SvController::resetAll().
npcap_set_duration_mode()
int npcap_set_duration_mode (uint32_t durationSeconds, int repeatEnabled, int repeatInfinite, uint32_t repeatCount)
Set duration and repeat mode.
Parameters
durationSeconds Duration in seconds (0 = continuous)
repeatEnabled Whether repeat mode is enabled
repeatInfinite If repeat, true = infinite loop
repeatCount Number of repeats (if not infinite)
Returns
0 on success
Set duration and repeat mode.
Parameters
durationSeconds - Duration in seconds (0 = continuous/infinite)
repeatEnabled - Whether repeat mode is enabled
repeatInfinite - If repeatEnabled, true = infinite loop
repeatCount - Number of times to repeat (if not infinite)
Returns
0 on success
Definition at line 827 of file sv_native_refactored.cc.
{
    std::lock_guard<std::mutex> lock(g_mutex);
    g_config.durationSeconds = durationSeconds;
    g_config.repeatEnabled = (repeatEnabled != 0);
    g_config.repeatInfinite = (repeatInfinite != 0);
    g_config.repeatCount = repeatCount;
    g_repeat_cycle.store(0);
    return 0;
}
References g_config, g_mutex, and g_repeat_cycle.
npcap_set_equations()
int npcap_set_equations (const char * equations)
Set channel equations Format: "id1:equation1|id2:equation2|...".
Parameters
equations Equation string
Returns
0 on success
Set channel equations Format: "id1:equation1|id2:equation2|...".
Parameters
equations - String format: "id1:equation1|id2:equation2|..."
Returns
0 on success, -1 on error
Definition at line 856 of file sv_native_refactored.cc.
{
    if (!equations) {
        snprintf(g_error_buffer, sizeof(g_error_buffer), "Null equations");
        return -1;
    }
    g_eq_processor.setDefaultFrequency(g_config.frequency);
    g_eq_processor.setSampleRate((uint32_t)g_config.sampleRate);
    std::lock_guard<std::mutex> lock(g_eq_mutex);
    return (g_eq_processor.loadEquations(equations) < 0) ? -1 : 0;
}
References g_config, g_eq_mutex, g_eq_processor(), and g_error_buffer.