SV Publisher - Native C++ Module: sv_native.h File Reference
sv_native.h File Reference
Header for Tauri FFI - C interface for Rust.
#include <stdint.h>
#include <stddef.h>
Data Structures
struct NpcapInterface
Network interface information.
struct TransmitStats
Transmission statistics.
Typedefs
typedef struct NpcapInterface NpcapInterface
Network interface information.
typedef struct TransmitStats TransmitStats
Transmission statistics.
Functions
const char * sv_get_last_error (void)
int npcap_list_interfaces (NpcapInterface *interfaces, int max_count)
List available network interfaces.
const char * npcap_get_last_error (void)
Get last error message.
int npcap_open (const char *device_name)
Open a network interface for transmission.
void npcap_close (void)
Close the currently open interface.
int npcap_is_open (void)
Check if an interface is open.
void npcap_stats_reset (void)
void npcap_stats_session_start (void)
void npcap_stats_session_end (void)
void npcap_stats_update_rates (void)
void npcap_stats_get (TransmitStats *stats)
uint64_t npcap_stats_get_duration_ms (void)
void npcap_stats_format_rate (double bps, char *buf, size_t buflen)
int npcap_publisher_configure (const char *svID, uint16_t appID, uint32_t confRev, uint8_t smpSynch, const uint8_t *srcMAC, const uint8_t *dstMAC, int vlanPriority, int vlanID, uint64_t sampleRate, double frequency, double voltageAmplitude, double currentAmplitude, uint8_t asduCount, uint8_t channelCount)
int npcap_publisher_start (void)
int npcap_publisher_stop (void)
int npcap_publisher_is_running (void)
int npcap_set_send_mode (int mode)
Set the packet sending mechanism.
int npcap_get_send_mode (void)
Get the current send mode.
int npcap_set_duration_mode (uint32_t durationSeconds, int repeatEnabled, int repeatInfinite, uint32_t repeatCount)
Set duration and repeat mode for publishing.
uint32_t npcap_get_remaining_seconds (void)
Get remaining time in seconds.
uint32_t npcap_get_current_repeat_cycle (void)
Get current repeat cycle number.
int npcap_is_duration_complete (void)
Check if duration has completed.
int npcap_set_equations (const char *equations)
Set equations for channels.
int npcap_get_sample_frame (uint8_t *outBuffer, size_t bufferSize, size_t *outFrameSize, uint32_t smpCnt)
Get a sample frame with current configuration Returns the actual encoded frame bytes that would be transmitted.
int npcap_get_current_channel_values (int32_t *outValues)
Get current channel values being transmitted.
uint32_t npcap_get_current_smp_cnt (void)
Get current sample count.
Detailed Description
Header for Tauri FFI - C interface for Rust.
Definition in file sv_native.h.
Typedef Documentation
NpcapInterface
typedef struct NpcapInterface NpcapInterface
Network interface information.
TransmitStats
typedef struct TransmitStats TransmitStats
Transmission statistics.
Function Documentation
npcap_close()
void npcap_close (void)
Close the currently open interface.
Definition at line 342 of file npcap_transmitter_impl.cc.
                       {
#ifdef _WIN32
    if (g_handle && g_close) { g_close(g_handle); g_handle = nullptr; }
#else
    if (g_handle) { pcap_close(g_handle); g_handle = nullptr; }
#endif
    printf("[npcap] Interface closed\n");
}
References g_close, and g_handle.
npcap_get_current_channel_values()
int npcap_get_current_channel_values (int32_t * outValues)
Get current channel values being transmitted.
Parameters
outValues - Array to receive 8 channel values (must be int32_t[8])
Returns
0 on success, -1 on error
Definition at line 907 of file sv_native_refactored.cc.
{
    if (!outValues) return -1;
    std::lock_guard<std::mutex> lock(g_channel_mutex);
    memcpy(outValues, g_channel_values, g_config.channelCount * sizeof(int32_t));
    return (int)g_config.channelCount;  // Return channel count
}
npcap_get_current_repeat_cycle()
uint32_t npcap_get_current_repeat_cycle (void)
Get current repeat cycle number.
Returns
Current cycle (0-based)
Definition at line 848 of file sv_native_refactored.cc.
{
    return g_repeat_cycle.load();
}
npcap_get_current_smp_cnt()
uint32_t npcap_get_current_smp_cnt (void)
Get current sample count.
Returns
Current sample count value
Definition at line 915 of file sv_native_refactored.cc.
{
    return g_current_smp_cnt.load();
}
npcap_get_last_error()
const char * npcap_get_last_error (void)
Get last error message.
Returns
Error string
Definition at line 263 of file npcap_transmitter_impl.cc.
{
    return g_error;
}
References g_error.
npcap_get_remaining_seconds()
uint32_t npcap_get_remaining_seconds (void)
Get remaining time in seconds.
Returns
Remaining seconds (0 if continuous mode or complete)
Definition at line 839 of file sv_native_refactored.cc.
{
    if (g_config.durationSeconds == 0 || !g_running.load()) return g_config.durationSeconds;
    uint64_t elapsed = get_time_ms() - g_start_time_ms.load();
    uint64_t duration = (uint64_t)g_config.durationSeconds * 1000ULL;
    return (elapsed >= duration) ? 0 : (uint32_t)((duration - elapsed) / 1000);
}
npcap_get_sample_frame()
int npcap_get_sample_frame (uint8_t * outBuffer, size_t bufferSize, size_t * outFrameSize, uint32_t smpCnt)
Get a sample frame with current configuration Returns the actual encoded frame bytes that would be transmitted.
Parameters
outBuffer - Buffer to receive frame bytes (should be at least 256 bytes)
bufferSize - Size of the output buffer
outFrameSize - Actual frame size written
smpCnt - Sample count to use (0 for current)
Returns
0 on success, -1 on error
Definition at line 869 of file sv_native_refactored.cc.
{
    if (!outBuffer || !outFrameSize || bufferSize < 64) return -1;
    SvEncoderConfig enc;
    {
        std::lock_guard<std::mutex> lock(g_mutex);
        strncpy(enc.svID, g_config.svID, sizeof(enc.svID) - 1);
        enc.appID = g_config.appID;
        enc.confRev = g_config.confRev;
        enc.smpSynch = g_config.smpSynch;
        memcpy(enc.srcMAC, g_config.srcMAC, 6);
        memcpy(enc.dstMAC, g_config.dstMAC, 6);
        enc.vlanPriority = g_config.vlanPriority;
        enc.vlanID = g_config.vlanID;
        enc.asduCount = 1;
        enc.channelCount = g_config.channelCount;
    }
    sv_encoder_set_config(&enc);
    int32_t samples[SV_MAX_CHANNELS] = {0};  // Support up to 20 channels
    double t = (double)smpCnt / (double)g_config.sampleRate;
    {
        std::lock_guard<std::mutex> lock(g_eq_mutex);
        g_eq_processor.generate9_2LESamples(t, samples, g_config.channelCount);
    }
    *outFrameSize = bufferSize;
    int result = sv_encoder_encode_packet(smpCnt, samples, outBuffer, outFrameSize);
    g_current_smp_cnt.store(smpCnt);
    {
        std::lock_guard<std::mutex> lock(g_channel_mutex);
        memcpy(g_channel_values, samples, g_config.channelCount * sizeof(int32_t));
    }
    return result;
}
npcap_get_send_mode()
int npcap_get_send_mode (void)
Get the current send mode.
Returns
Current mode (0=auto, 1=sendqueue, 2=sendpacket)
Definition at line 939 of file sv_native_refactored.cc.
{
    return (int)g_config.sendMode;
}
References g_config.
npcap_is_duration_complete()
int npcap_is_duration_complete (void)
Check if duration has completed.
Returns
1 if complete, 0 if still running
Definition at line 852 of file sv_native_refactored.cc.
{
    return g_duration_complete.load() ? 1 : 0;
}
npcap_is_open()
int npcap_is_open (void)
Check if an interface is open.
Returns
1 if open, 0 if not
Definition at line 351 of file npcap_transmitter_impl.cc.
{
    return g_handle ? 1 : 0;
}
References g_handle.
Referenced by npcap_publisher_start(), and SvController::startAll().
npcap_list_interfaces()
int npcap_list_interfaces (NpcapInterface * interfaces, int max_count)
List available network interfaces.
Parameters
interfaces Array to store interface info
max_count Maximum number of interfaces to return
Returns
Number of interfaces found, or -1 on error
Definition at line 180 of file npcap_transmitter_impl.cc.
{
    printf("[npcap] Listing network interfaces...\n");
#ifdef _WIN32
    if (!npcap_load_dll()) return -1;
    pcap_if_t* alldevs = nullptr;
    char errbuf[256] = {0};
    if (g_findalldevs(&alldevs, errbuf) == -1) {
        snprintf(g_error, sizeof(g_error), "pcap_findalldevs failed: %s", errbuf);
        printf("[npcap] ERROR: %s\n", g_error);
        return -1;
    }
    if (!alldevs) {
        printf("[npcap] WARNING: No interfaces found by pcap_findalldevs\n");
        return 0;
    }
    int count = 0;
    for (pcap_if_t* d = alldevs; d && count < max_count; d = d->next) {
        NpcapInterface* iface = &interfaces[count];
        memset(iface, 0, sizeof(NpcapInterface));
        if (d->name) {
            strncpy(iface->name, d->name, sizeof(iface->name) - 1);
        }
        if (d->description) {
            strncpy(iface->description, d->description, sizeof(iface->description) - 1);
        }
        /* Get MAC address from Windows adapter info */
        PIP_ADAPTER_INFO adapterInfo = nullptr;
        ULONG bufLen = 0;
        if (GetAdaptersInfo(adapterInfo, &bufLen) == ERROR_BUFFER_OVERFLOW) {
            adapterInfo = (PIP_ADAPTER_INFO)malloc(bufLen);
            if (adapterInfo && GetAdaptersInfo(adapterInfo, &bufLen) == NO_ERROR) {
                for (PIP_ADAPTER_INFO ai = adapterInfo; ai; ai = ai->Next) {
                    printf("[npcap] Checking: pcap='%s' vs adapter='%s'\n", d->name, ai->AdapterName);
                    if (d->name && strstr(d->name, ai->AdapterName)) {
                        memcpy(iface->mac, ai->Address, 6);
                        iface->has_mac = 1;
                        printf("[npcap] MAC found: %02X:%02X:%02X:%02X:%02X:%02X\n",
                               iface->mac[0], iface->mac[1], iface->mac[2],
                               iface->mac[3], iface->mac[4], iface->mac[5]);
                        break;
                    }
                }
            }
            if (adapterInfo) free(adapterInfo);
        }
        printf("[npcap] Interface %d: %s (has_mac=%d)\n", count,
               iface->description[0] ? iface->description : iface->name, iface->has_mac);
        count++;
    }
    g_freealldevs(alldevs);
    printf("[npcap] Total: %d interfaces found\n", count);
    return count;
#else
    pcap_if_t* alldevs;
    char errbuf[PCAP_ERRBUF_SIZE];
    if (pcap_findalldevs(&alldevs, errbuf) == -1) {
        snprintf(g_error, sizeof(g_error), "%s", errbuf);
        return -1;
    }
    int count = 0;
    for (pcap_if_t* d = alldevs; d && count < max_count; d = d->next) {
        NpcapInterface* iface = &interfaces[count++];
        memset(iface, 0, sizeof(NpcapInterface));
        if (d->name) strncpy(iface->name, d->name, sizeof(iface->name) - 1);
        if (d->description) strncpy(iface->description, d->description, sizeof(iface->description) - 1);
    }
    pcap_freealldevs(alldevs);
    return count;
#endif
}
References NpcapInterface::description, g_error, g_findalldevs, g_freealldevs, NpcapInterface::has_mac, NpcapInterface::mac, NpcapInterface::name, pcap_if::next, and npcap_load_dll().
npcap_open()
int npcap_open (const char * device_name)
Open a network interface for transmission.
Parameters
device_name Device name (e.g., "\\Device\\NPF_{GUID}")
Returns
0 on success, -1 on error
Definition at line 267 of file npcap_transmitter_impl.cc.
{
    printf("[npcap] Opening: %s\n", device_name);
#ifdef _WIN32
    if (!npcap_load_dll()) return -1;
    if (g_handle) { g_close(g_handle); g_handle = nullptr; }
    char errbuf[256];
    /* Prefer pcap_create workflow to enable HOST_HIPREC timestamps.
     * HOST_HIPREC uses QPC internally in Npcap kernel driver for
     * microsecond-precision timestamps — no need for manual QPC. */
    if (g_pcap_create && g_set_snaplen && g_set_promisc &&
        g_set_timeout && g_set_tstamp_type && g_activate) {
        g_handle = g_pcap_create(device_name, errbuf);
        if (!g_handle) {
            snprintf(g_error, sizeof(g_error), "pcap_create: %s", errbuf);
            return -1;
        }
        g_set_snaplen(g_handle, 65536);
        g_set_promisc(g_handle, 1);
        g_set_timeout(g_handle, 1);
        /* Set high-precision timestamp type (HOST_HIPREC = QPC-based) */
        int tstamp_ret = g_set_tstamp_type(g_handle, PCAP_TSTAMP_HOST_HIPREC);
        if (tstamp_ret == 0) {
            printf("[npcap] HOST_HIPREC timestamp enabled\n");
        } else {
            printf("[npcap] HOST_HIPREC not supported (code=%d), using default\n", tstamp_ret);
        }
        /* Immediate mode: minimize driver-level send/receive buffering.
         * Critical for USB Ethernet adapters to reduce packet batching. */
        if (g_set_immediate_mode) {
            g_set_immediate_mode(g_handle, 1);
            printf("[npcap] Immediate mode enabled (reduced buffering)\n");
        }
        int activate_ret = g_activate(g_handle);
        if (activate_ret < 0) {
            snprintf(g_error, sizeof(g_error), "pcap_activate failed (code=%d)", activate_ret);
            g_close(g_handle);
            g_handle = nullptr;
            return -1;
        }
        if (activate_ret > 0) {
            printf("[npcap] pcap_activate warning (code=%d)\n", activate_ret);
        }
        printf("[npcap] Interface opened (pcap_create + HOST_HIPREC)\n");
    } else {
        /* Fallback to pcap_open_live if pcap_create not available */
        g_handle = g_open_live(device_name, 65536, 1, 1, errbuf);
        if (!g_handle) {
            snprintf(g_error, sizeof(g_error), "pcap_open_live: %s", errbuf);
            return -1;
        }
        printf("[npcap] Interface opened (pcap_open_live fallback)\n");
    }
#else
    char errbuf[PCAP_ERRBUF_SIZE];
    g_handle = pcap_open_live(device_name, 65536, 1, 1, errbuf);
    if (!g_handle) {
        snprintf(g_error, sizeof(g_error), "%s", errbuf);
        return -1;
    }
    printf("[npcap] Interface opened\n");
#endif
    return 0;
}
References g_activate, g_close, g_error, g_handle, g_open_live, g_pcap_create, g_set_immediate_mode, g_set_promisc, g_set_snaplen, g_set_timeout, g_set_tstamp_type, npcap_load_dll(), and PCAP_TSTAMP_HOST_HIPREC.
npcap_publisher_configure()
int npcap_publisher_configure (const char * svID, uint16_t appID, uint32_t confRev, uint8_t smpSynch, const uint8_t * srcMAC, const uint8_t * dstMAC, int vlanPriority, int vlanID, uint64_t sampleRate, double frequency, double voltageAmplitude, double currentAmplitude, uint8_t asduCount, uint8_t channelCount)
Definition at line 710 of file sv_native_refactored.cc.
  {
    printf("[publisher] Configure: svID=%s, rate=%llu Hz, channels=%d\n", svID, (unsigned long long)sampleRate, channelCount);
    std::lock_guard<std::mutex> lock(g_mutex);
    memset(g_config.svID, 0, sizeof(g_config.svID));
    if (svID && strlen(svID) > 0) {
        strncpy(g_config.svID, svID, sizeof(g_config.svID) - 1);
    } else {
        strncpy(g_config.svID, "MU01", sizeof(g_config.svID) - 1);
    }
    g_config.appID = appID;
    g_config.confRev = confRev;
    g_config.smpSynch = smpSynch;
    memcpy(g_config.srcMAC, srcMAC, 6);
    memcpy(g_config.dstMAC, dstMAC, 6);
    g_config.vlanPriority = vlanPriority;
    g_config.vlanID = vlanID;
    g_config.sampleRate = sampleRate;
    g_config.frequency = frequency;
    g_config.voltageAmplitude = voltageAmplitude;
    g_config.currentAmplitude = currentAmplitude;
    g_config.asduCount = (asduCount == 1 || asduCount == 4 || asduCount == 8) ? asduCount : 1;
    g_config.channelCount = (channelCount >= 1 && channelCount <= SV_MAX_CHANNELS) ? channelCount : 8;
    g_eq_processor.setDefaultFrequency(frequency);
    g_eq_processor.setSampleRate((uint32_t)sampleRate);
    return 0;
}
References g_config, g_eq_processor(), g_mutex, and SV_MAX_CHANNELS.
npcap_publisher_is_running()
int npcap_publisher_is_running (void)
Definition at line 823 of file sv_native_refactored.cc.
{
    return g_running.load() ? 1 : 0;
}
npcap_publisher_start()
int npcap_publisher_start (void)
Definition at line 753 of file sv_native_refactored.cc.
{
    if (!npcap_is_open()) {
        snprintf(g_error_buffer, sizeof(g_error_buffer), "No interface open");
        return -1;
    }
    if (g_running.load()) return 0;
    if (sv_mp_is_running()) {
        snprintf(g_error_buffer, sizeof(g_error_buffer),
                 "Multi-publisher is already running. Stop it before using single-publisher.");
        return -1;
    }
    g_start_time_ms.store(get_time_ms());
    g_duration_complete.store(false);
    g_running.store(true);
    /* Dispatch based on configured send mode */
    switch (g_config.sendMode) {
        case SEND_MODE_QUEUE:
            /* Force SendQueue (batch) mode */
            if (npcap_sendqueue_available()) {
                printf("[publisher] Mode: FORCED SendQueue (batch)\n");
                g_thread = std::thread(publisher_loop_batch);
            } else {
                printf("[publisher] WARNING: SendQueue requested but not available, falling back to single\n");
                g_thread = std::thread(publisher_loop_single);
            }
            break;
        case SEND_MODE_PACKET:
            /* Force SendPacket (immediate) mode */
            printf("[publisher] Mode: FORCED SendPacket (immediate)\n");
            g_thread = std::thread(publisher_loop_immediate);
            break;
        case SEND_MODE_USB:
            /* USB-Optimized: immediate + forced SPIN + minimum gap */
            printf("[publisher] Mode: USB-OPTIMIZED (spin pacing + min gap)\n");
            g_thread = std::thread(publisher_loop_immediate);
            break;
        case SEND_MODE_AUTO:
        default:
            /* Auto-detect: use SendQueue if available, else fall back to single */
            if (npcap_sendqueue_available()) {
                printf("[publisher] Mode: AUTO -> SendQueue (batch)\n");
                g_thread = std::thread(publisher_loop_batch);
            } else {
                printf("[publisher] Mode: AUTO -> single (no sendqueue)\n");
                g_thread = std::thread(publisher_loop_single);
            }
            break;
    }
    return 0;
}
npcap_publisher_stop()
int npcap_publisher_stop (void)
Definition at line 812 of file sv_native_refactored.cc.
{
    if (!g_running.load()) return 0;
    g_running.store(false);
    if (g_thread.joinable()) g_thread.join();
    free_frame_cache();
    return 0;
}
npcap_set_duration_mode()
int npcap_set_duration_mode (uint32_t durationSeconds, int repeatEnabled, int repeatInfinite, uint32_t repeatCount)
Set duration and repeat mode for publishing.
Parameters
durationSeconds - Duration in seconds (0 = continuous/infinite)
repeatEnabled - Whether repeat mode is enabled
repeatInfinite - If repeatEnabled, true = infinite loop
repeatCount - Number of times to repeat (if not infinite)
Returns
0 on success
Definition at line 827 of file sv_native_refactored.cc.
{
    std::lock_guard<std::mutex> lock(g_mutex);
    g_config.durationSeconds = durationSeconds;
    g_config.repeatEnabled = (repeatEnabled != 0);
    g_config.repeatInfinite = (repeatInfinite != 0);
    g_config.repeatCount = repeatCount;
    g_repeat_cycle.store(0);
    return 0;
}
npcap_set_equations()
int npcap_set_equations (const char * equations)
Set equations for channels.
Parameters
equations - String format: "id1:equation1|id2:equation2|..."
Returns
0 on success, -1 on error
Definition at line 856 of file sv_native_refactored.cc.
{
    if (!equations) {
        snprintf(g_error_buffer, sizeof(g_error_buffer), "Null equations");
        return -1;
    }
    g_eq_processor.setDefaultFrequency(g_config.frequency);
    g_eq_processor.setSampleRate((uint32_t)g_config.sampleRate);
    std::lock_guard<std::mutex> lock(g_eq_mutex);
    return (g_eq_processor.loadEquations(equations) < 0) ? -1 : 0;
}
npcap_set_send_mode()
int npcap_set_send_mode (int mode)
Set the packet sending mechanism.
Parameters
mode - 0=AUTO (sendqueue if available, else single), 1=SENDQUEUE (force batch mode, best for PCIe NICs), 2=SENDPACKET (force immediate mode, best for USB adapters)
Returns
0 on success, -1 on error (invalid mode or publishing in progress)
Definition at line 919 of file sv_native_refactored.cc.
{
    if (mode < 0 || mode > 3) {
        snprintf(g_error_buffer, sizeof(g_error_buffer), "Invalid send mode: %d (0=auto, 1=queue, 2=packet, 3=usb)", mode);
        return -1;
    }
    if (g_running.load()) {
        snprintf(g_error_buffer, sizeof(g_error_buffer), "Cannot change send mode while publishing");
        return -1;
    }
    std::lock_guard<std::mutex> lock(g_mutex);
    g_config.sendMode = (uint8_t)mode;
    const char* mode_names[] = { "AUTO", "SendQueue (batch)", "SendPacket (immediate)", "USB-Optimized (spin+gap)" };
    printf("[publisher] Send mode set to: %s (%d)\n", mode_names[mode], mode);
    return 0;
}
References g_config, g_error_buffer, g_mutex, and g_running.
npcap_stats_format_rate()
void npcap_stats_format_rate (double bps, char * buf, size_t buflen)
Definition at line 103 of file sv_stats_impl.cc.
{
    if (bps >= 1e9)      snprintf(buf, buflen, "%.2f Gbps", bps / 1e9);
    else if (bps >= 1e6) snprintf(buf, buflen, "%.2f Mbps", bps / 1e6);
    else if (bps >= 1e3) snprintf(buf, buflen, "%.2f Kbps", bps / 1e3);
    else                 snprintf(buf, buflen, "%.0f bps", bps);
}
npcap_stats_get()
void npcap_stats_get (TransmitStats * stats)
Definition at line 84 of file sv_stats_impl.cc.
{
    std::lock_guard<std::mutex> lock(g_mutex);
    memcpy(stats, &g_stats, sizeof(TransmitStats));
}
npcap_stats_get_duration_ms()
uint64_t npcap_stats_get_duration_ms (void)
Definition at line 89 of file sv_stats_impl.cc.
{
    std::lock_guard<std::mutex> lock(g_mutex);
    if (g_stats.session_start_ms == 0) return 0;
    if (g_stats.session_active) {
        return npcap_stats_get_time_ms() - g_stats.session_start_ms;
    }
    if (g_stats.session_end_ms > 0) {
        return g_stats.session_end_ms - g_stats.session_start_ms;
    }
    return 0;
}
npcap_stats_reset()
void npcap_stats_reset (void)
Definition at line 37 of file sv_stats_impl.cc.
{
    std::lock_guard<std::mutex> lock(g_mutex);
    memset(&g_stats, 0, sizeof(g_stats));
}
npcap_stats_session_end()
void npcap_stats_session_end (void)
Definition at line 53 of file sv_stats_impl.cc.
{
    std::lock_guard<std::mutex> lock(g_mutex);
    g_stats.session_end_ms = npcap_stats_get_time_ms();
    g_stats.session_active = 0;
}
npcap_stats_session_start()
void npcap_stats_session_start (void)
Definition at line 42 of file sv_stats_impl.cc.
{
    std::lock_guard<std::mutex> lock(g_mutex);
    g_stats.session_start_ms = npcap_stats_get_time_ms();
    g_stats.session_end_ms = 0;
    g_stats.rate_window_start_ms = g_stats.session_start_ms;
    g_stats.rate_bytes_sent = 0;
    g_stats.rate_packets_sent = 0;
    g_stats.session_active = 1;
}
npcap_stats_update_rates()
void npcap_stats_update_rates (void)
Definition at line 60 of file sv_stats_impl.cc.
{
    std::lock_guard<std::mutex> lock(g_mutex);
    uint64_t now = npcap_stats_get_time_ms();
    uint64_t elapsed = now - g_stats.rate_window_start_ms;
    /* Update every 250ms */
    if (elapsed >= 250) {
        double seconds = elapsed / 1000.0;
        if (seconds > 0) {
            g_stats.current_bps = (g_stats.rate_bytes_sent * 8.0) / seconds;
            g_stats.current_pps = g_stats.rate_packets_sent / seconds;
            if (g_stats.current_bps > g_stats.peak_bps) g_stats.peak_bps = g_stats.current_bps;
            if (g_stats.current_pps > g_stats.peak_pps) g_stats.peak_pps = g_stats.current_pps;
        }
        /* Reset window */
        g_stats.rate_window_start_ms = now;
        g_stats.rate_bytes_sent = 0;
        g_stats.rate_packets_sent = 0;
    }
}
sv_get_last_error()
const char * sv_get_last_error (void)
Definition at line 706 of file sv_native_refactored.cc.
{
    return g_error_buffer;
}
References g_error_buffer.